export type SessionIdentity = { employee: { id: string; displayName: string; role: string }; csrfToken: string };
const apiOrigin = import.meta.env.VITE_API_ORIGIN ?? "http://127.0.0.1:8787";
async function request<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(`${apiOrigin}${path}`, { credentials: "include", headers: { "content-type": "application/json", ...(init?.headers ?? {}) }, ...init }); if (!response.ok) throw new Error((await response.json().catch(() => null))?.message ?? "تعذر إتمام الطلب."); return response.status === 204 ? (undefined as T) : response.json() as Promise<T>; }
export const login = (email: string, password: string) => request<SessionIdentity>("/api/auth/login", { method: "POST", body: JSON.stringify({ email, password }) });
export const getSession = () => request<SessionIdentity>("/api/auth/me");
export const logout = (csrfToken: string) => request<void>("/api/auth/logout", { method: "POST", headers: { "x-csrf-token": csrfToken } });
export type CustomerRow={id:string;name:string;customerCode:string|null;classification:string;operationalStatus:string;isActive:boolean;openCommitments:number};
export type Commitment={id:string;title:string;dueAt:string;status:string;urgency:string;completionEvidence?:string;resultingCommitmentId?:string;attention:string};
export type LifecycleSummary={id:string;status:string;blockedReason?:string|null;responsibleParty?:string|null;followUpAt?:string|null;closedAt?:string|null;resolvedAt?:string|null;updatedAt?:string|null;classification?:string};
export type CustomerFile={customer:CustomerRow & {contactName?:string;phone?:string;city?:string;operationalNotes?:string};commitments:Commitment[];orders:LifecycleSummary[];complaints:LifecycleSummary[]};
export const customers=()=>request<CustomerRow[]>("/api/customers"); export const customerFile=(id:string)=>request<CustomerFile>(`/api/customers/${id}`);
export type RepDay={visits:Array<{id:string;customerId:string;customerName:string;plannedAt:string;purpose:string;status:string;outcome?:string}>;commitments:Array<{id:string;title:string;dueAt:string;status:string;urgency:string}>;close:Record<string,number>};
export const representativeDay=()=>request<RepDay>("/api/representative/day");
export const startVisit=(id:string,csrfToken:string)=>request(`/api/visits/${id}/start`,{method:"POST",headers:{"x-csrf-token":csrfToken}});
export const completeVisit=(id:string,csrfToken:string,input:{outcome:string;evidence:string;followUpTitle?:string;followUpDueAt?:string})=>request(`/api/visits/${id}/complete`,{method:"POST",headers:{"x-csrf-token":csrfToken},body:JSON.stringify(input)});
export const captureOperational=(type:"opportunity"|"collection"|"complaint"|"observation",csrfToken:string,input:Record<string,unknown>)=>request(`/api/${type}s`,{method:"POST",headers:{"x-csrf-token":csrfToken},body:JSON.stringify(input)});
export const createOrder=(csrfToken:string,input:Record<string,unknown>)=>request("/api/orders",{method:"POST",headers:{"x-csrf-token":csrfToken},body:JSON.stringify(input)});
export const initiateReactivation=(id:string,csrfToken:string,input:Record<string,unknown>)=>request(`/api/customers/${id}/reactivation`,{method:"POST",headers:{"x-csrf-token":csrfToken},body:JSON.stringify(input)});
export type LifecycleDetail={order?:any;complaint?:any;history:Array<any>;resultingWork:Array<any>};
export const orderLifecycle=(id:string)=>request<LifecycleDetail>(`/api/orders/${id}/lifecycle`);
export const complaintLifecycle=(id:string)=>request<LifecycleDetail>(`/api/complaints/${id}/lifecycle`);
export const transitionOrder=(id:string,csrf:string,input:Record<string,unknown>)=>request<LifecycleDetail>(`/api/orders/${id}/lifecycle`,{method:"POST",headers:{"x-csrf-token":csrf},body:JSON.stringify(input)});
export const transitionComplaint=(id:string,csrf:string,input:Record<string,unknown>)=>request<any>(`/api/complaints/${id}/lifecycle`,{method:"POST",headers:{"x-csrf-token":csrf},body:JSON.stringify(input)});
export type TelesalesCall={id:string;customerId:string;customerName:string;purpose:string;priorityReason:string;scheduledAt:string;state:string;todayNoAnswers?:number};
export type TelesalesDetail={call:TelesalesCall & {contactName?:string;phone?:string;operationalNotes?:string};attempts:Array<{outcome:string;result:string;evidence:string;attemptedAt:string}>;commitments:Array<{id:string;title:string;dueAt:string;status:string;evidence?:string}>;allowedOutcomes:string[]};
export const telesalesQueue=()=>request<TelesalesCall[]>("/api/telesales/queue");
export const telesalesDetail=(id:string)=>request<TelesalesDetail>(`/api/telesales/calls/${id}`);
export const telesalesDay=()=>request<Record<string,number>>("/api/telesales/day");
export const telesalesActivity=()=>request<Array<{id:string;outcome:string;result:string;evidence:string;at:string;priorityReason:string;customerName:string}>>("/api/telesales/activity");
export const startTelesalesCall=(id:string,csrfToken:string)=>request(`/api/telesales/calls/${id}/start`,{method:"POST",headers:{"x-csrf-token":csrfToken}});
export const completeTelesalesCall=(id:string,csrfToken:string,input:{outcome:string;evidence:string;callbackAt?:string})=>request<{id:string;result:string;nextCallId?:string}>(`/api/telesales/calls/${id}/complete`,{method:"POST",headers:{"x-csrf-token":csrfToken},body:JSON.stringify(input)});
export const telesalesProducts=()=>request<Array<{id:string;name:string;referenceCode:string}>>("/api/telesales/products");
export const telesalesCapture=(callId:string,kind:"order"|"collection"|"complaint"|"opportunity"|"reactivation",csrfToken:string,input:Record<string,unknown>)=>request<any>(`/api/telesales/calls/${callId}/${kind}`,{method:"POST",headers:{"x-csrf-token":csrfToken},body:JSON.stringify(input)});
export type SupervisorWorkspace={team:Array<{id:string;displayName:string;queuedCalls:number;completedCalls:number}>;exceptions:Array<{id:string;kind:string;severity:string;summary:string;evidence:string;requiredNextAction:string;status:string;version:number;sourceType:string;sourceId:string;employeeName?:string;customerName?:string;priorAction?:string;priorActionEvidence?:string;followUpAt?:string;operationallyOpen:boolean}>;checkpoints:Array<{checkpoint:string;evidence:string;readinessState:string;at:string}>;quality:Array<{id:string;employeeName:string;evidence:string;result:string;observation:string}>;coaching:Array<{id:string;employeeName:string;topic:string;evidence:string;agreedAction:string;dueAt?:string;status:string}>};
export const supervisorWorkspace=()=>request<SupervisorWorkspace>("/api/supervisor/workspace");
export const supervisorAction=(id:string,csrf:string,input:Record<string,unknown>)=>request<any>(`/api/supervisor/exceptions/${id}/actions`,{method:"POST",headers:{"x-csrf-token":csrf},body:JSON.stringify(input)});
export const supervisorCheckpoint=(csrf:string,input:Record<string,unknown>)=>request<any>("/api/supervisor/checkpoints",{method:"POST",headers:{"x-csrf-token":csrf},body:JSON.stringify(input)});
export const supervisorQuality=(csrf:string,input:Record<string,unknown>)=>request<any>("/api/supervisor/quality-reviews",{method:"POST",headers:{"x-csrf-token":csrf},body:JSON.stringify(input)});
export const supervisorCoaching=(csrf:string,input:Record<string,unknown>)=>request<any>("/api/supervisor/coaching",{method:"POST",headers:{"x-csrf-token":csrf},body:JSON.stringify(input)});
