/** Complete PostgreSQL Phase 4 complaint-domain acceptance. Run after migrations/bootstrap/Phase 1 + 2 seeds. */
import assert from "node:assert/strict";
import test from "node:test";
import {randomUUID} from "node:crypto";
import postgres from "postgres";
import {PostgresIdentityRepository} from "../src/repository";
import {AuditService} from "../src/audit";
import {CustomerCommitmentService,type Actor} from "../src/customer-commitment";
import {RepresentativeService} from "../src/representative";
import {OrderLifecycleService} from "../src/order-lifecycle";
import {ComplaintLifecycleService} from "../src/complaint-lifecycle";
import {createApi} from "../src/app";

const url=process.env.DATABASE_URL;if(!url)throw new Error("DATABASE_URL is required for test:api:phase4.");
const sql=postgres(url,{max:10}),repository=new PostgresIdentityRepository(sql),audit=new AuditService(repository),commitments=new CustomerCommitmentService(sql,audit),representative=new RepresentativeService(sql,audit,commitments),orders=new OrderLifecycleService(sql,audit,commitments),complaints=new ComplaintLifecycleService(sql,audit,commitments);
async function fixture(label:string){
 const employee=await repository.findEmployeeByEmail("rep@local.test");assert.ok(employee);
 const actor:Actor={id:employee.id,organizationId:employee.organizationId!,teamId:employee.teamId,role:"sales_representative"};
 const customer=(await sql<any[]>`SELECT id FROM customers WHERE owner_employee_id=${actor.id} AND is_active=true ORDER BY created_at LIMIT 1`)[0];assert.ok(customer);
 const complaintId=randomUUID();
 await sql`INSERT INTO complaints(id,organization_id,customer_id,recorded_by_employee_id,classification,description,required_action) VALUES(${complaintId},${actor.organizationId},${customer.id},${actor.id},'unclassified',${`Phase4 complaint ${label}`},'Investigate root cause')`;
 return {actor,customerId:customer.id,complaintId,dueAt:new Date(Date.now()+86_400_000).toISOString()};
}
const classify=(version:number)=>({to:"classified" as const,evidence:"Classification evidence",classification:"quality",version});
const assign=(version:number)=>({to:"assigned" as const,evidence:"Assignment evidence",responsibleParty:"Customer care",version});
const corrective=(version:number)=>({to:"corrective_action" as const,evidence:"Corrective evidence",correctiveAction:"Replace affected stock and inspect batch",responsibleParty:"Customer care",version});
const follow=(dueAt:string,version:number,key= randomUUID())=>({to:"follow_up" as const,evidence:"Follow-up evidence",responsibleParty:"Customer care",followUpAt:dueAt,followUpTitle:"Confirm corrective action with customer",createFollowUp:true,followUpIdempotencyKey:key,version});
async function toCorrective(f:Awaited<ReturnType<typeof fixture>>){await complaints.transition(f.actor,f.complaintId,classify(1),"classify");await complaints.transition(f.actor,f.complaintId,assign(2),"assign");await complaints.transition(f.actor,f.complaintId,corrective(3),"corrective");}
async function counts(id:string){return {events:(await sql<any[]>`SELECT count(*)::int AS count FROM complaint_lifecycle_events WHERE complaint_id=${id}`)[0].count,commitments:(await sql<any[]>`SELECT count(*)::int AS count FROM commitments WHERE source_type='complaint' AND source_id=${id}`)[0].count,audits:(await sql<any[]>`SELECT count(*)::int AS count FROM audit_events WHERE resource_id=${id} AND action='complaint.follow_up'`)[0].count};}

test("recorded complaint is open and classifies then assigns without resolving",async()=>{const f=await fixture("classify");const initial=await complaints.detail(f.actor,f.complaintId);assert.equal(initial.complaint.status,"recorded");assert.equal(initial.complaint.operationallyOpen,true);await complaints.transition(f.actor,f.complaintId,classify(1),"classify");let detail=await complaints.detail(f.actor,f.complaintId);assert.equal(detail.complaint.status,"classified");assert.equal(detail.complaint.classification,"quality");assert.equal(detail.complaint.operationallyOpen,true);assert.equal(detail.complaint.resolution,null);await complaints.transition(f.actor,f.complaintId,assign(2),"assign");detail=await complaints.detail(f.actor,f.complaintId);assert.equal(detail.complaint.status,"assigned");assert.equal(detail.complaint.responsibleParty,"Customer care");assert.equal(detail.complaint.operationallyOpen,true);});
test("corrective action is explicit, evidenced, actor-attributed, and does not resolve",async()=>{const f=await fixture("corrective");await toCorrective(f);const detail=await complaints.detail(f.actor,f.complaintId);assert.equal(detail.complaint.status,"corrective_action");assert.equal(detail.complaint.correctiveAction,"Replace affected stock and inspect batch");assert.equal(detail.complaint.operationallyOpen,true);assert.equal(detail.complaint.resolution,null);assert.equal(detail.history.at(-1)?.to,"corrective_action");assert.ok(detail.history.at(-1)?.actorEmployeeId);assert.equal((await sql<any[]>`SELECT count(*)::int AS count FROM audit_events WHERE resource_id=${f.complaintId} AND action='complaint.corrective_action'`)[0].count,1);});
test("invalid skips, repeats, stale versions, and premature resolution are rejected",async()=>{const f=await fixture("invalid");await assert.rejects(()=>complaints.transition(f.actor,f.complaintId,{to:"assigned",evidence:"skip",responsibleParty:"care",version:1},"skip"),{statusCode:422});await assert.rejects(()=>complaints.transition(f.actor,f.complaintId,{to:"resolved",evidence:"premature",responsibleParty:"care",version:1},"premature"),{statusCode:422});await complaints.transition(f.actor,f.complaintId,classify(1),"classify");await assert.rejects(()=>complaints.transition(f.actor,f.complaintId,classify(2),"repeat"),{statusCode:422});await assert.rejects(()=>complaints.transition(f.actor,f.complaintId,assign(1),"stale"),{statusCode:409});});
test("follow-up atomically creates a canonical linked Commitment and remains unresolved",async()=>{const f=await fixture("follow");await toCorrective(f);const result=await complaints.transition(f.actor,f.complaintId,follow(f.dueAt,4),"follow");assert.ok(result.commitmentId);const detail=await complaints.detail(f.actor,f.complaintId);assert.equal(detail.complaint.status,"follow_up");assert.equal(detail.complaint.operationallyOpen,true);assert.equal(detail.complaint.resolution,null);assert.equal(detail.resultingWork.length,1);assert.equal(detail.resultingWork[0].id,result.commitmentId);assert.deepEqual((await sql<any[]>`SELECT source_type AS "sourceType",source_id AS "sourceId",source_evidence AS "sourceEvidence" FROM commitments WHERE id=${result.commitmentId}`)[0],{sourceType:"complaint",sourceId:f.complaintId,sourceEvidence:"Follow-up evidence"});});
test("dependent follow-up failure rolls back complaint transition, event, linked work, and audit",async()=>{const f=await fixture("rollback");await toCorrective(f);const before=await counts(f.complaintId);await sql`CREATE OR REPLACE FUNCTION phase4_reject_complaint_commitment() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'forced complaint commitment failure'; END $$`;await sql`CREATE TRIGGER phase4_reject_complaint_commitment BEFORE INSERT ON commitments FOR EACH ROW EXECUTE FUNCTION phase4_reject_complaint_commitment()`;try{await assert.rejects(()=>complaints.transition(f.actor,f.complaintId,follow(f.dueAt,4),"forced"));}finally{await sql`DROP TRIGGER IF EXISTS phase4_reject_complaint_commitment ON commitments`;await sql`DROP FUNCTION IF EXISTS phase4_reject_complaint_commitment()`;}assert.deepEqual(await counts(f.complaintId),before);assert.deepEqual((await sql<any[]>`SELECT status,version FROM complaints WHERE id=${f.complaintId}`)[0],{status:"corrective_action",version:4});});
test("valid retry after rollback creates exactly one intended follow-up result",async()=>{const f=await fixture("retry");await toCorrective(f);await sql`CREATE OR REPLACE FUNCTION phase4_reject_complaint_commitment() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'forced complaint commitment failure'; END $$`;await sql`CREATE TRIGGER phase4_reject_complaint_commitment BEFORE INSERT ON commitments FOR EACH ROW EXECUTE FUNCTION phase4_reject_complaint_commitment()`;try{await assert.rejects(()=>complaints.transition(f.actor,f.complaintId,follow(f.dueAt,4),"forced"));}finally{await sql`DROP TRIGGER IF EXISTS phase4_reject_complaint_commitment ON commitments`;await sql`DROP FUNCTION IF EXISTS phase4_reject_complaint_commitment()`;}await complaints.transition(f.actor,f.complaintId,follow(f.dueAt,4),"retry");assert.deepEqual(await counts(f.complaintId),{events:4,commitments:1,audits:1});});
test("resolution is explicit and remains operationally open until a separate valid closure",async()=>{const f=await fixture("resolve");await toCorrective(f);await complaints.transition(f.actor,f.complaintId,follow(f.dueAt,4),"follow");await assert.rejects(()=>complaints.transition(f.actor,f.complaintId,{to:"resolved",evidence:"",responsibleParty:"Customer care",version:5},"missing"),{statusCode:422});const resolved=await complaints.transition(f.actor,f.complaintId,{to:"resolved",evidence:"Customer confirmed corrective action",responsibleParty:"Customer care",version:5},"resolve");assert.equal(resolved.version,6);let detail=await complaints.detail(f.actor,f.complaintId);assert.equal(detail.complaint.status,"resolved");assert.equal(detail.complaint.operationallyOpen,true);assert.ok(detail.complaint.resolution?.at);assert.equal(detail.complaint.closure,null);await assert.rejects(()=>complaints.transition(f.actor,f.complaintId,{to:"closed",evidence:"",responsibleParty:"Customer care",version:6},"close-missing"),{statusCode:422});await assert.rejects(()=>complaints.transition(f.actor,f.complaintId,{to:"closed",evidence:"Closure proof",version:6},"close-owner"),{statusCode:422});detail=await complaints.transition(f.actor,f.complaintId,{to:"closed",evidence:"Closure confirmed and recorded",responsibleParty:"Customer care",version:6},"close");assert.equal(detail.version,7);const complete=await complaints.detail(f.actor,f.complaintId);assert.equal(complete.complaint.status,"closed");assert.equal(complete.complaint.operationallyOpen,false);assert.equal(complete.complaint.closure?.evidence,"Closure confirmed and recorded");assert.ok(complete.complaint.closure?.at);assert.equal(complete.history.at(-1)?.to,"closed");});
test("scoped roles can inspect complaint evidence while only the owning Representative can mutate lifecycle",async()=>{const f=await fixture("auth");const foreignId=randomUUID();await sql`INSERT INTO employees(id,organization_id,team_id,email,display_name,password_hash,role) VALUES(${foreignId},${f.actor.organizationId},${f.actor.teamId},${`phase4-complaint-${foreignId}@test.local`},'foreign','x','sales_representative')`;await assert.rejects(()=>complaints.detail({...f.actor,id:foreignId},f.complaintId),{statusCode:404});for(const role of ["sales_manager","telesales_supervisor","telesales_employee"] as const)assert.equal((await complaints.detail({...f.actor,role},f.complaintId)).complaint.id,f.complaintId);await assert.rejects(()=>complaints.transition({...f.actor,role:"sales_manager"},f.complaintId,classify(1),"manager-write"),{statusCode:403});await assert.rejects(()=>complaints.transition({...f.actor,role:"telesales_supervisor"},f.complaintId,classify(1),"supervisor-write"),{statusCode:403});assert.equal((await complaints.detail(f.actor,f.complaintId)).complaint.id,f.complaintId);});
test("complaint API requires authentication and CSRF for state-changing lifecycle writes",async()=>{const f=await fixture("api");const app=await createApi({repository,sales:commitments,representative,orders,complaints});try{assert.equal((await app.inject({method:"POST",url:`/api/complaints/${f.complaintId}/lifecycle`,payload:classify(1)})).statusCode,401);const login=await app.inject({method:"POST",url:"/api/auth/login",payload:{email:"rep@local.test",password:"Phase0-password!"}});const cookie=Array.isArray(login.headers["set-cookie"])?login.headers["set-cookie"][0]:login.headers["set-cookie"];assert.ok(cookie);assert.equal((await app.inject({method:"POST",url:`/api/complaints/${f.complaintId}/lifecycle`,headers:{cookie},payload:classify(1)})).statusCode,403);assert.equal((await app.inject({method:"POST",url:`/api/complaints/${f.complaintId}/lifecycle`,headers:{cookie,"x-csrf-token":login.json().csrfToken},payload:classify(1)})).statusCode,200);}finally{await app.close();}});
test.after(async()=>{await sql.end();});
