/** Complete PostgreSQL Phase 4 order-domain acceptance. Run after migrations/bootstrap/Phase 1 + 2 seeds. */
import assert from "node:assert/strict";
import test from "node:test";
import {randomUUID} from "node:crypto";
import postgres from "postgres";
import {PostgresIdentityRepository} from "../src/repository";
import {AuditService} from "../src/audit";
import {CustomerCommitmentService,type Actor} from "../src/customer-commitment";
import {RepresentativeService} from "../src/representative";
import {OrderLifecycleService} from "../src/order-lifecycle";
import {createApi} from "../src/app";

const url=process.env.DATABASE_URL;if(!url)throw new Error("DATABASE_URL is required for test:api:phase4.");
const sql=postgres(url,{max:10}),repository=new PostgresIdentityRepository(sql),audit=new AuditService(repository),commitments=new CustomerCommitmentService(sql,audit),representative=new RepresentativeService(sql,audit,commitments),orders=new OrderLifecycleService(sql,audit,commitments);
const stageEvidence=(stage:string)=>`Evidence for ${stage}`;
async function fixture(label:string,requiresCreditReview=false){
 const employee=await repository.findEmployeeByEmail("rep@local.test");assert.ok(employee);
 const actor:Actor={id:employee.id,organizationId:employee.organizationId!,teamId:employee.teamId,role:"sales_representative"};
 const customer=(await sql<any[]>`SELECT id FROM customers WHERE owner_employee_id=${actor.id} AND is_active=true ORDER BY created_at LIMIT 1`)[0];assert.ok(customer);
 const product=(await sql<any[]>`SELECT id FROM products WHERE organization_id=${actor.organizationId} AND active=true ORDER BY created_at LIMIT 1`)[0];assert.ok(product);
 const created=await representative.createOrder(actor,{customerId:customer.id,productId:product.id,quantity:1,duplicateOverrideReason:`PHASE4 ${label}`,requiresCreditReview},`phase4-${label}`);
 return {actor,customerId:customer.id,orderId:created.id,dueAt:new Date(Date.now()+86_400_000).toISOString()};
}
const blockInput=(dueAt:string,key:string,version=1)=>({reason:"Credit review requires confirmation",responsibleParty:"Credit control",requiredNextAction:"Confirm customer credit evidence",evidence:"Customer limit needs verification",followUpAt:dueAt,createFollowUp:true,followUpIdempotencyKey:key,version});
async function advance(actor:Actor,id:string,stages:string[],version=1){let current=version;for(const to of stages){await orders.transition(actor,id,{to:to as any,evidence:stageEvidence(to),responsibleParty:`Owner ${to}`,version:current},`transition-${to}`);current+=1;}return current;}
async function counts(orderId:string){return {events:(await sql<any[]>`SELECT count(*)::int AS count FROM order_lifecycle_events WHERE order_id=${orderId}`)[0].count,commitments:(await sql<any[]>`SELECT count(*)::int AS count FROM commitments WHERE source_type='order' AND source_id=${orderId}`)[0].count,blockedAudits:(await sql<any[]>`SELECT count(*)::int AS count FROM audit_events WHERE resource_id=${orderId} AND action='order.blocked'`)[0].count};}

test("recorded orders expose the canonical initial read model",async()=>{const f=await fixture("initial");const detail=await orders.detail(f.actor,f.orderId);assert.equal(detail.order.status,"recorded");assert.equal(detail.order.requiresCreditReview,false);assert.equal(detail.order.operationallyOpen,true);assert.deepEqual(detail.order.block,{active:false,reason:null,responsibleParty:null,requiredNextAction:null,followUpAt:null});assert.equal(detail.history.length,0);});
test("normal orders progress through every required canonical stage with ordered evidence and audits",async()=>{const f=await fixture("normal");const version=await advance(f.actor,f.orderId,["approved","preparation","delivery_preparation","delivered"]);assert.equal(version,5);const detail=await orders.detail(f.actor,f.orderId);assert.equal(detail.order.status,"delivered");assert.equal(detail.order.operationallyOpen,true);assert.ok(detail.order.delivered?.at);assert.equal(detail.order.closure,null);assert.deepEqual(detail.history.map(x=>x.to),["approved","preparation","delivery_preparation","delivered"]);assert.ok(detail.history.every(x=>x.evidence&&x.actorEmployeeId&&x.at));assert.equal((await sql<any[]>`SELECT count(*)::int AS count FROM audit_events WHERE resource_id=${f.orderId} AND action='order.lifecycle_transition'`)[0].count,4);});
test("credit-review orders require the conditional review step while non-review orders cannot invent it",async()=>{const review=await fixture("review",true);await assert.rejects(()=>orders.transition(review.actor,review.orderId,{to:"approved",evidence:"skip",version:1},"skip"),{statusCode:422});await advance(review.actor,review.orderId,["credit_review","approved"]);const normal=await fixture("no-review");await assert.rejects(()=>orders.transition(normal.actor,normal.orderId,{to:"credit_review",evidence:"unneeded",version:1},"unneeded"),{statusCode:422});});
test("invalid, skipped, repeated, and stale lifecycle transitions are rejected server-side",async()=>{const f=await fixture("invalid");await assert.rejects(()=>orders.transition(f.actor,f.orderId,{to:"preparation",evidence:"skip",version:1},"skip"),{statusCode:422});await orders.transition(f.actor,f.orderId,{to:"approved",evidence:"approved",version:1},"approved");await assert.rejects(()=>orders.transition(f.actor,f.orderId,{to:"approved",evidence:"repeat",version:2},"repeat"),{statusCode:422});await assert.rejects(()=>orders.transition(f.actor,f.orderId,{to:"preparation",evidence:"stale",version:1},"stale"),{statusCode:409});});
test("blocked orders persist canonical metadata, linked work, and remain open without closing",async()=>{const f=await fixture("block");const blocked=await orders.block(f.actor,f.orderId,blockInput(f.dueAt,randomUUID()),"block");assert.ok(blocked.commitmentId);const detail=await orders.detail(f.actor,f.orderId);assert.equal(detail.order.status,"recorded");assert.equal(detail.order.operationallyOpen,true);assert.equal(detail.order.block.active,true);assert.equal(detail.order.block.reason,"Credit review requires confirmation");assert.equal(detail.resultingWork.length,1);assert.equal(detail.resultingWork[0].id,blocked.commitmentId);assert.equal((await sql<any[]>`SELECT source_type AS "sourceType",source_id AS "sourceId" FROM commitments WHERE id=${blocked.commitmentId}`)[0].sourceType,"order");assert.equal((await sql<any[]>`SELECT source_id AS "sourceId" FROM commitments WHERE id=${blocked.commitmentId}`)[0].sourceId,f.orderId);});
test("dependent Commitment failure rolls back order metadata, event, source linkage, and success audit",async()=>{const f=await fixture("rollback");const before=await counts(f.orderId);await sql`CREATE OR REPLACE FUNCTION phase4_reject_order_commitment() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'forced order commitment failure'; END $$`;await sql`CREATE TRIGGER phase4_reject_order_commitment BEFORE INSERT ON commitments FOR EACH ROW EXECUTE FUNCTION phase4_reject_order_commitment()`;try{await assert.rejects(()=>orders.block(f.actor,f.orderId,blockInput(f.dueAt,randomUUID()),"forced"));}finally{await sql`DROP TRIGGER IF EXISTS phase4_reject_order_commitment ON commitments`;await sql`DROP FUNCTION IF EXISTS phase4_reject_order_commitment()`;}assert.deepEqual(await counts(f.orderId),before);const row=(await sql<any[]>`SELECT blocked_reason,version FROM sales_orders WHERE id=${f.orderId}`)[0];assert.equal(row.blocked_reason,null);assert.equal(row.version,1);});
test("valid retry after rollback creates exactly one intended order event and commitment",async()=>{const f=await fixture("retry");await sql`CREATE OR REPLACE FUNCTION phase4_reject_order_commitment() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'forced order commitment failure'; END $$`;await sql`CREATE TRIGGER phase4_reject_order_commitment BEFORE INSERT ON commitments FOR EACH ROW EXECUTE FUNCTION phase4_reject_order_commitment()`;try{await assert.rejects(()=>orders.block(f.actor,f.orderId,blockInput(f.dueAt,randomUUID()),"forced"));}finally{await sql`DROP TRIGGER IF EXISTS phase4_reject_order_commitment ON commitments`;await sql`DROP FUNCTION IF EXISTS phase4_reject_order_commitment()`;}await orders.block(f.actor,f.orderId,blockInput(f.dueAt,randomUUID()),"retry");assert.deepEqual(await counts(f.orderId),{events:1,commitments:1,blockedAudits:1});});
test("unblock is explicit, preserves history and resulting work, and does not advance lifecycle",async()=>{const f=await fixture("unblock");await orders.block(f.actor,f.orderId,blockInput(f.dueAt,randomUUID()),"block");const result=await orders.unblock(f.actor,f.orderId,{evidence:"Credit review evidence received",version:2},"unblock");assert.equal(result.version,3);const detail=await orders.detail(f.actor,f.orderId);assert.equal(detail.order.status,"recorded");assert.equal(detail.order.block.active,false);assert.equal(detail.order.operationallyOpen,true);assert.equal(detail.history.length,2);assert.equal(detail.resultingWork.length,1);assert.equal((await sql<any[]>`SELECT count(*)::int AS count FROM audit_events WHERE resource_id=${f.orderId} AND action='order.unblocked'`)[0].count,1);});
test("closure is only possible after delivered and requires evidence, responsible party, and a current version",async()=>{const premature=await fixture("premature");await assert.rejects(()=>orders.transition(premature.actor,premature.orderId,{to:"closed",evidence:"no",responsibleParty:"Ops",version:1},"premature"),{statusCode:422});const f=await fixture("closure");const deliveredVersion=await advance(f.actor,f.orderId,["approved","preparation","delivery_preparation","delivered"]);await assert.rejects(()=>orders.transition(f.actor,f.orderId,{to:"closed",evidence:"",responsibleParty:"Ops",version:deliveredVersion},"no-evidence"),{statusCode:422});await assert.rejects(()=>orders.transition(f.actor,f.orderId,{to:"closed",evidence:"closed proof",version:deliveredVersion},"no-owner"),{statusCode:422});const detail=await orders.transition(f.actor,f.orderId,{to:"closed",evidence:"Delivery and handover confirmed",responsibleParty:"Delivery operations",version:deliveredVersion},"closed");assert.equal(detail.order.status,"closed");assert.equal(detail.order.operationallyOpen,false);assert.ok(detail.order.closure?.at);assert.equal(detail.order.closure?.evidence,"Delivery and handover confirmed");assert.equal(detail.order.closure?.responsibleParty,"Delivery operations");assert.equal(detail.history.at(-1)?.to,"closed");assert.equal((await sql<any[]>`SELECT count(*)::int AS count FROM audit_events WHERE resource_id=${f.orderId} AND action='order.lifecycle_transition'`)[0].count,5);});
test("scoped roles can inspect order evidence while only the owning Representative can mutate lifecycle",async()=>{const f=await fixture("auth");const foreignId=randomUUID();await sql`INSERT INTO employees(id,organization_id,team_id,email,display_name,password_hash,role) VALUES(${foreignId},${f.actor.organizationId},${f.actor.teamId},${`phase4-foreign-${foreignId}@test.local`},'foreign','x','sales_representative')`;const foreign:Actor={...f.actor,id:foreignId};await assert.rejects(()=>orders.detail(foreign,f.orderId),{statusCode:404});for(const role of ["sales_manager","telesales_supervisor","telesales_employee"] as const)assert.equal((await orders.detail({...f.actor,role},f.orderId)).order.id,f.orderId);await assert.rejects(()=>orders.transition({...f.actor,role:"sales_manager"},f.orderId,{to:"approved",evidence:"manager read only",version:1},"manager-write"),{statusCode:403});await assert.rejects(()=>orders.block({...f.actor,role:"telesales_supervisor"},f.orderId,blockInput(f.dueAt,randomUUID()),"supervisor-write"),{statusCode:403});assert.ok((await orders.detail(f.actor,f.orderId)).order.id===f.orderId);});
test("order API requires authentication and CSRF for lifecycle writes",async()=>{const f=await fixture("api");const app=await createApi({repository,sales:commitments,representative,orders});try{assert.equal((await app.inject({method:"GET",url:`/api/orders/${f.orderId}/lifecycle`})).statusCode,401);const login=await app.inject({method:"POST",url:"/api/auth/login",payload:{email:"rep@local.test",password:"Phase0-password!"}});assert.equal(login.statusCode,200);const cookie=Array.isArray(login.headers["set-cookie"])?login.headers["set-cookie"][0]:login.headers["set-cookie"];assert.ok(cookie);assert.equal((await app.inject({method:"POST",url:`/api/orders/${f.orderId}/lifecycle`,headers:{cookie},payload:{to:"approved",evidence:"api proof",version:1}})).statusCode,403);const token=login.json().csrfToken;assert.equal((await app.inject({method:"POST",url:`/api/orders/${f.orderId}/lifecycle`,headers:{cookie,"x-csrf-token":token},payload:{to:"approved",evidence:"api proof",version:1}})).statusCode,200);}finally{await app.close();}});
test.after(async()=>{await sql.end();});
