import assert from "node:assert/strict";
import test from "node:test";
import { randomUUID } from "node:crypto";
import postgres from "postgres";
import { PostgresIdentityRepository } from "../src/repository";
import { AuditService } from "../src/audit";
import { CustomerCommitmentService, type Actor } from "../src/customer-commitment";
import { SupervisorService } from "../src/supervisor";
import { createApi } from "../src/app";

const url=process.env.DATABASE_URL;if(!url)throw new Error("DATABASE_URL is required for test:api:phase5.");const sql=postgres(url),repo=new PostgresIdentityRepository(sql),audit=new AuditService(repo),commitments=new CustomerCommitmentService(sql,audit),supervisor=new SupervisorService(sql,audit,commitments);
async function fixture(label:string){const supervisorRow=(await sql<any[]>`SELECT id,organization_id AS "organizationId",team_id AS "teamId" FROM employees WHERE role='telesales_supervisor' ORDER BY created_at LIMIT 1`)[0];const employee=(await sql<any[]>`SELECT id FROM employees WHERE team_id=${supervisorRow.teamId} AND role='telesales_employee' LIMIT 1`)[0];const call=(await sql<any[]>`SELECT id,customer_id AS "customerId" FROM telesales_calls WHERE owner_employee_id=${employee.id} LIMIT 1`)[0];const id=randomUUID();await sql`INSERT INTO supervisor_exceptions(id,organization_id,team_id,subject_employee_id,customer_id,source_type,source_id,kind,severity,summary,evidence,required_next_action) VALUES(${id},${supervisorRow.organizationId},${supervisorRow.teamId},${employee.id},${call.customerId},'telesales_call',${call.id},${`phase5_${label}_${randomUUID()}`},'urgent',${`Phase5 ${label}`},'source evidence','follow up with customer')`;return{actor:{id:supervisorRow.id,organizationId:supervisorRow.organizationId,teamId:supervisorRow.teamId,role:"telesales_supervisor"} as Actor,id,employeeId:employee.id,callId:call.id};}
test("team-scoped workspace returns persisted exceptions and three checkpoints",async()=>{const f=await fixture("workspace");const work=await supervisor.workspace(f.actor);assert.ok(work.exceptions.some(x=>x.id===f.id));assert.equal(work.checkpoints.length,3);assert.ok(work.exceptions.find(x=>x.id===f.id)?.operationallyOpen);});
test("foreign team and unsupported roles are denied server-side",async()=>{const f=await fixture("auth");await assert.rejects(()=>supervisor.workspace({...f.actor,teamId:randomUUID()}),{statusCode:403});await assert.rejects(()=>supervisor.workspace({...f.actor,role:"telesales_employee"}),{statusCode:403});});
test("checkpoint evidence persists with team scope and audit",async()=>{const f=await fixture("checkpoint");const result=await supervisor.recordCheckpoint(f.actor,{checkpoint:"morning",evidence:"readiness evidence",readinessState:"attention"},"phase5-checkpoint");assert.ok(result.id);assert.equal((await sql<any[]>`SELECT count(*)::int AS count FROM supervisor_checkpoints WHERE id=${result.id}`)[0].count,1);});
test("escalation and follow-up record action while exception remains operationally open",async()=>{const f=await fixture("open");const escalated=await supervisor.action(f.actor,f.id,{kind:"escalate",evidence:"escalation evidence",version:1},"phase5-escalate");assert.equal(escalated.operationallyOpen,true);const followed=await supervisor.action(f.actor,f.id,{kind:"follow_up",evidence:"follow-up evidence",followUpAt:new Date(Date.now()+86400000).toISOString(),followUpTitle:"follow up with customer",version:2,idempotencyKey:randomUUID()},"phase5-follow");assert.equal(followed.operationallyOpen,true);assert.ok(followed.commitmentId);assert.equal((await sql<any[]>`SELECT status FROM supervisor_exceptions WHERE id=${f.id}`)[0].status,"actioned");});
test("only explicit resolving action closes eligible supervisor exception",async()=>{const f=await fixture("resolve");const result=await supervisor.action(f.actor,f.id,{kind:"resolve",evidence:"genuine completion proof",version:1},"phase5-resolve");assert.equal(result.operationallyOpen,false);assert.equal((await sql<any[]>`SELECT status FROM supervisor_exceptions WHERE id=${f.id}`)[0].status,"resolved");});
test("quality review and coaching persist without resolving source exception",async()=>{const f=await fixture("quality");await supervisor.qualityReview(f.actor,{employeeId:f.employeeId,sourceType:"telesales_call",sourceId:f.callId,evidence:"review proof",result:"needs_improvement",observation:"follow-up clarity"},"phase5-quality");const coached=await supervisor.coach(f.actor,{employeeId:f.employeeId,sourceType:"telesales_call",sourceId:f.callId,topic:"closing call",evidence:"coaching proof",agreedAction:"state next commitment",dueAt:new Date(Date.now()+86400000).toISOString(),createFollowUp:true,idempotencyKey:randomUUID()},"phase5-coach");assert.ok(coached.commitmentId);assert.equal((await sql<any[]>`SELECT status FROM supervisor_exceptions WHERE id=${f.id}`)[0].status,"open");assert.equal((await sql<any[]>`SELECT count(*)::int AS count FROM supervisor_quality_reviews WHERE source_id=${f.callId}`)[0].count>0,true);});
test("stale version rejects without partial action",async()=>{const f=await fixture("conflict");await supervisor.action(f.actor,f.id,{kind:"escalate",evidence:"first action",version:1},"phase5-first");await assert.rejects(()=>supervisor.action(f.actor,f.id,{kind:"resolve",evidence:"stale",version:1},"phase5-stale"),{statusCode:409});assert.equal((await sql<any[]>`SELECT count(*)::int AS count FROM supervisor_actions WHERE exception_id=${f.id}`)[0].count,1);});
test("forced Commitment failure rolls back Supervisor action, linkage, and success audit",async()=>{const f=await fixture("rollback");const before=await sql<any[]>`SELECT version,status FROM supervisor_exceptions WHERE id=${f.id}`;await sql`CREATE OR REPLACE FUNCTION phase5_reject_commitment() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'forced supervisor commitment failure'; END $$`;await sql`CREATE TRIGGER phase5_reject_commitment BEFORE INSERT ON commitments FOR EACH ROW EXECUTE FUNCTION phase5_reject_commitment()`;try{await assert.rejects(()=>supervisor.action(f.actor,f.id,{kind:"follow_up",evidence:"forced",followUpAt:new Date(Date.now()+86400000).toISOString(),followUpTitle:"follow up",version:1,idempotencyKey:randomUUID()},"phase5-forced"));}finally{await sql`DROP TRIGGER IF EXISTS phase5_reject_commitment ON commitments`;await sql`DROP FUNCTION IF EXISTS phase5_reject_commitment()`;}assert.deepEqual(await sql<any[]>`SELECT version,status FROM supervisor_exceptions WHERE id=${f.id}`,before);assert.equal((await sql<any[]>`SELECT count(*)::int AS count FROM supervisor_actions WHERE exception_id=${f.id}`)[0].count,0);assert.equal((await sql<any[]>`SELECT count(*)::int AS count FROM audit_events WHERE resource_id=${f.id} AND action='supervisor.exception_action'`)[0].count,0);});
test("acknowledgement persists evidence/history/audit and remains operationally open",async()=>{const f=await fixture("ack");const result=await supervisor.action(f.actor,f.id,{kind:"acknowledge",evidence:"acknowledgement proof",version:1},"phase5-ack");assert.equal(result.operationallyOpen,true);assert.equal((await sql<any[]>`SELECT status,version FROM supervisor_exceptions WHERE id=${f.id}`)[0].status,"actioned");const row=(await sql<any[]>`SELECT kind,evidence,actor_employee_id AS "actorId",created_at AS "at" FROM supervisor_actions WHERE id=${result.actionId}`)[0];assert.deepEqual({kind:row.kind,evidence:row.evidence,actorId:row.actorId},{kind:"acknowledge",evidence:"acknowledgement proof",actorId:f.actor.id});assert.ok(row.at);assert.equal((await sql<any[]>`SELECT count(*)::int AS count FROM audit_events WHERE resource_id=${f.id} AND action='supervisor.exception_action'`)[0].count,1);});
test("same-team reassignment remains open while foreign reassignment has no residue",async()=>{const f=await fixture("reassign");const result=await supervisor.action(f.actor,f.id,{kind:"reassign",ownerEmployeeId:f.employeeId,followUpAt:new Date(Date.now()+86400000).toISOString(),followUpTitle:"reassignment follow-up",evidence:"reassignment proof",version:1,idempotencyKey:randomUUID()},"phase5-reassign");assert.equal(result.operationallyOpen,true);assert.equal((await sql<any[]>`SELECT subject_employee_id AS "employeeId",status FROM supervisor_exceptions WHERE id=${f.id}`)[0].employeeId,f.employeeId);const foreignTeam=randomUUID(),foreignEmployee=randomUUID();await sql`INSERT INTO teams(id,organization_id,name) VALUES(${foreignTeam},${f.actor.organizationId},'foreign team')`;await sql`INSERT INTO employees(id,organization_id,team_id,email,display_name,password_hash,role) VALUES(${foreignEmployee},${f.actor.organizationId},${foreignTeam},${`foreign-${foreignEmployee}@test.local`},'foreign','x','telesales_employee')`;const before=(await sql<any[]>`SELECT version FROM supervisor_exceptions WHERE id=${f.id}`)[0].version;await assert.rejects(()=>supervisor.action(f.actor,f.id,{kind:"reassign",ownerEmployeeId:foreignEmployee,followUpAt:new Date(Date.now()+86400000).toISOString(),followUpTitle:"bad",evidence:"bad",version:before,idempotencyKey:randomUUID()},"phase5-foreign-reassign"),{statusCode:403});assert.equal((await sql<any[]>`SELECT version FROM supervisor_exceptions WHERE id=${f.id}`)[0].version,before);});
test("foreign-team canonical Commitment assignment is denied without action or audit residue",async()=>{const f=await fixture("foreign-commitment");const foreignTeam=randomUUID(),foreignEmployee=randomUUID();await sql`INSERT INTO teams(id,organization_id,name) VALUES(${foreignTeam},${f.actor.organizationId},'foreign commitment team')`;await sql`INSERT INTO employees(id,organization_id,team_id,email,display_name,password_hash,role) VALUES(${foreignEmployee},${f.actor.organizationId},${foreignTeam},${`foreign-commitment-${foreignEmployee}@test.local`},'foreign','x','telesales_employee')`;await assert.rejects(()=>supervisor.action(f.actor,f.id,{kind:"follow_up",ownerEmployeeId:foreignEmployee,followUpAt:new Date(Date.now()+86400000).toISOString(),followUpTitle:"bad",evidence:"bad",version:1,idempotencyKey:randomUUID()},"phase5-foreign-commitment"),{statusCode:403});assert.equal((await sql<any[]>`SELECT count(*)::int AS count FROM supervisor_actions WHERE exception_id=${f.id}`)[0].count,0);assert.equal((await sql<any[]>`SELECT count(*)::int AS count FROM commitments WHERE source_type='supervisor_exception' AND source_id=${f.id}`)[0].count,0);});
test("Phase 5 HTTP writes require auth and valid CSRF, then accept authorized Supervisor",async()=>{const f=await fixture("http");const email=(await sql<any[]>`SELECT email FROM employees WHERE id=${f.actor.id}`)[0].email;const app=await createApi({repository:repo,sales:commitments,supervisor});try{assert.equal((await app.inject({method:"POST",url:`/api/supervisor/exceptions/${f.id}/actions`,payload:{kind:"acknowledge",evidence:"x",version:1}})).statusCode,401);const login=await app.inject({method:"POST",url:"/api/auth/login",payload:{email,password:"Phase0-password!"}});const cookie=Array.isArray(login.headers["set-cookie"])?login.headers["set-cookie"][0]:login.headers["set-cookie"];assert.equal((await app.inject({method:"POST",url:`/api/supervisor/exceptions/${f.id}/actions`,headers:{cookie},payload:{kind:"acknowledge",evidence:"http proof",version:1}})).statusCode,403);assert.equal((await app.inject({method:"POST",url:`/api/supervisor/exceptions/${f.id}/actions`,headers:{cookie,"x-csrf-token":"invalid"},payload:{kind:"acknowledge",evidence:"http proof",version:1}})).statusCode,403);assert.equal((await app.inject({method:"POST",url:`/api/supervisor/exceptions/${f.id}/actions`,headers:{cookie,"x-csrf-token":login.json().csrfToken},payload:{kind:"acknowledge",evidence:"http proof",version:1}})).statusCode,200);}finally{await app.close();}});
test("valid retry after dependent failure creates exactly one action, Commitment, and success audit",async()=>{const f=await fixture("retry-once");const key=randomUUID(),input={kind:"follow_up" as const,evidence:"retry proof",followUpAt:new Date(Date.now()+86400000).toISOString(),followUpTitle:"retry follow-up",version:1,idempotencyKey:key};await sql`CREATE OR REPLACE FUNCTION phase5_retry_reject() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'forced retry failure'; END $$`;await sql`CREATE TRIGGER phase5_retry_reject BEFORE INSERT ON commitments FOR EACH ROW EXECUTE FUNCTION phase5_retry_reject()`;try{await assert.rejects(()=>supervisor.action(f.actor,f.id,input,"phase5-retry-fail"));}finally{await sql`DROP TRIGGER IF EXISTS phase5_retry_reject ON commitments`;await sql`DROP FUNCTION IF EXISTS phase5_retry_reject()`;}await supervisor.action(f.actor,f.id,input,"phase5-retry-success");assert.equal((await sql<any[]>`SELECT count(*)::int AS count FROM supervisor_actions WHERE exception_id=${f.id}`)[0].count,1);assert.equal((await sql<any[]>`SELECT count(*)::int AS count FROM commitments WHERE source_type='supervisor_exception' AND source_id=${f.id}`)[0].count,1);assert.equal((await sql<any[]>`SELECT count(*)::int AS count FROM audit_events WHERE resource_id=${f.id} AND action='supervisor.exception_action'`)[0].count,1);});
test.after(async()=>sql.end());
