import assert from "node:assert/strict";
import test from "node:test";
import { randomUUID } from "node:crypto";
import postgres from "postgres";
import { PostgresIdentityRepository } from "../src/repository";
import { AuditService } from "../src/audit";
import { CustomerCommitmentService, type Actor } from "../src/customer-commitment";
import { RepresentativeService } from "../src/representative";
import { TelesalesService } from "../src/telesales";

const url=process.env.DATABASE_URL;if(!url)throw new Error("DATABASE_URL is required for test:api:phase3.");
const sql=postgres(url),repo=new PostgresIdentityRepository(sql),audit=new AuditService(repo),sales=new CustomerCommitmentService(sql,audit),rep=new RepresentativeService(sql,audit,sales),tele=new TelesalesService(sql,audit,sales);
let actor:Actor,org:string,customer:string;
async function setup(){const e=await repo.findEmployeeByEmail("telesales@local.test");assert.ok(e);actor={id:e.id,organizationId:e.organizationId!,teamId:e.teamId,role:"telesales_employee"};org=actor.organizationId;customer=(await sql<any[]>`SELECT id FROM customers WHERE owner_employee_id=${actor.id} LIMIT 1`)[0].id}
async function createCall(purpose="routine",at=new Date()){const id=randomUUID();await sql`INSERT INTO telesales_calls(id,organization_id,customer_id,owner_employee_id,purpose,priority_reason,scheduled_at) VALUES(${id},${org},${customer},${actor.id},${purpose},${purpose},${at})`;return id}
test.before(setup);
test("queue ranks every persisted priority and exposes explainable reason",async()=>{const q=await tele.queue(actor),r=q.map(x=>x.purpose);for(const [a,b] of [["supervisor_priority","collection"],["collection","complaint_followup"],["complaint_followup","reactivation"],["reactivation","opportunity"],["opportunity","routine"]])assert.ok(r.indexOf(a)<r.indexOf(b),`${a} before ${b}`);assert.ok(q.every(x=>x.priorityReason));});
test("queue enforces role and ownership scope",async()=>{await assert.rejects(()=>tele.queue({...actor,role:"sales_representative"}),{statusCode:403});const foreign=randomUUID(),email=`foreign-${foreign}@test.local`;await sql`INSERT INTO employees(id,organization_id,team_id,email,display_name,password_hash,role) SELECT ${foreign},organization_id,team_id,${email},'foreign','x','telesales_employee' FROM employees WHERE id=${actor.id}`;const id=randomUUID();await sql`INSERT INTO telesales_calls(id,organization_id,customer_id,owner_employee_id,purpose,priority_reason,scheduled_at) VALUES(${id},${org},${customer},${foreign},'routine','foreign',now())`;assert.ok(!(await tele.queue(actor)).some(x=>x.id===id));await assert.rejects(()=>tele.detail(actor,id),{statusCode:404});});
test("start persists live state and rejects repeat or invalid start",async()=>{const id=await createCall();await tele.start(actor,id,"start");assert.equal((await sql<any[]>`SELECT state FROM telesales_calls WHERE id=${id}`)[0].state,"in_progress");await assert.rejects(()=>tele.start(actor,id,"again"),{statusCode:409});await assert.rejects(()=>tele.start(actor,randomUUID(),"missing"),{statusCode:409});});
test("complete persists explicit outcome and evidence and rejects repeat",async()=>{const id=await createCall();await tele.start(actor,id,"x");await tele.complete(actor,id,{outcome:"successful_contact",evidence:"explicit"},"x");assert.deepEqual((await sql<any[]>`SELECT state,last_outcome AS "outcome",evidence FROM telesales_calls WHERE id=${id}`)[0],{state:"completed",outcome:"successful_contact",evidence:"explicit"});await assert.rejects(()=>tele.complete(actor,id,{outcome:"successful_contact",evidence:"again"},"x"),{statusCode:409});});
test("historical no-answer excluded; first and second create exactly one same-day retry",async()=>{const id=await createCall();await sql`INSERT INTO telesales_call_attempts(id,call_id,organization_id,employee_id,attempted_at,outcome,result,evidence) VALUES(${randomUUID()},${id},${org},${actor.id},now()-interval '1 day','no_answer','followup','old')`;await tele.start(actor,id,"x");const a=await tele.complete(actor,id,{outcome:"no_answer",evidence:"first"},"x");assert.equal((await sql<any[]>`SELECT count(*)::int AS n FROM telesales_call_attempts WHERE call_id=${id} AND outcome='no_answer' AND attempted_at::date=current_date`)[0].n,1);assert.ok(a.nextCallId);await tele.start(actor,a.nextCallId!,"x");const b=await tele.complete(actor,a.nextCallId!,{outcome:"no_answer",evidence:"second"},"x");assert.equal(b.result,"followup");assert.ok(b.nextCallId);});
test("third no-answer escalates, retains outcome, creates no fourth retry, and dual-reports",async()=>{const id=await createCall();await tele.start(actor,id,"x");const a=await tele.complete(actor,id,{outcome:"no_answer",evidence:"one"},"x");await tele.start(actor,a.nextCallId!,"x");const b=await tele.complete(actor,a.nextCallId!,{outcome:"no_answer",evidence:"two"},"x");await tele.start(actor,b.nextCallId!,"x");const c=await tele.complete(actor,b.nextCallId!,{outcome:"no_answer",evidence:"three"},"x");assert.equal(c.result,"escalated");assert.equal(c.nextCallId,null);assert.deepEqual((await sql<any[]>`SELECT last_outcome AS "outcome",last_result AS "result" FROM telesales_calls WHERE id=${b.nextCallId}`)[0],{outcome:"no_answer",result:"escalated"});const d=await tele.day(actor);assert.ok(Number(d.noAnswer)>=3&&Number(d.escalations)>=1);});
test("callback creates persisted same-day work without no-answer inflation; future callback is not active",async()=>{const id=await createCall();await tele.start(actor,id,"x");const same=await tele.complete(actor,id,{outcome:"callback",evidence:"same",callbackAt:new Date(Date.now()+3600000).toISOString()},"x");assert.ok((await tele.queue(actor)).some(x=>x.id===same.nextCallId));const future=await createCall();await tele.start(actor,future,"x");const f=await tele.complete(actor,future,{outcome:"callback",evidence:"future",callbackAt:new Date(Date.now()+172800000).toISOString()},"x");assert.ok(!(await tele.queue(actor)).some(x=>x.id===f.nextCallId));assert.ok((await sql<any[]>`SELECT id FROM telesales_calls WHERE id=${f.nextCallId}`)[0]);});
test("canonical order validates product and quantity, detects duplicate, and records override audit",async()=>{const p=(await rep.products(actor))[0],orderCustomer=randomUUID();assert.ok(p);await sql`INSERT INTO customers(id,organization_id,owner_employee_id,owner_team_id,name,classification,operational_status,is_active) VALUES(${orderCustomer},${org},${actor.id},${actor.teamId},${`order-${orderCustomer}`},'follow_up','normal',true)`;await assert.rejects(()=>rep.createOrder(actor,{customerId:orderCustomer,quantity:1},"x"));await assert.rejects(()=>rep.createOrder(actor,{customerId:orderCustomer,productId:p.id,quantity:0},"x"));const one=await rep.createOrder(actor,{customerId:orderCustomer,productId:p.id,quantity:1},"x");assert.ok((await sql<any[]>`SELECT id FROM sales_order_items WHERE order_id=${one.id}`)[0]);const before=(await sql<any[]>`SELECT count(*)::int AS n FROM sales_orders WHERE customer_id=${orderCustomer}`)[0].n;await assert.rejects(()=>rep.createOrder(actor,{customerId:orderCustomer,productId:p.id,quantity:1},"x"),{statusCode:409});assert.equal((await sql<any[]>`SELECT count(*)::int AS n FROM sales_orders WHERE customer_id=${orderCustomer}`)[0].n,before);const two=await rep.createOrder(actor,{customerId:orderCustomer,productId:p.id,quantity:1,duplicateOverrideReason:"override"},"x");assert.ok((await repo.listAudit()).some(x=>x.resourceId===two.id&&x.action==="order.recorded"));});
test("payment promise atomically persists source, commitment and audit; invalid leaves no residue",async()=>{const due=new Date(Date.now()+86400000).toISOString(),before=(await sql<any[]>`SELECT count(*)::int AS n FROM collection_outcomes`)[0].n;await assert.rejects(()=>rep.capture(actor,"collection",{customerId:customer,outcome:"promise",promiseAmount:10,evidence:"missing"},"x"),{statusCode:422});assert.equal((await sql<any[]>`SELECT count(*)::int AS n FROM collection_outcomes`)[0].n,before);const r=await rep.capture(actor,"collection",{customerId:customer,outcome:"promise",promiseAmount:10,promiseDueAt:due,evidence:"promise",followUpTitle:"follow",followUpDueAt:due},"x");assert.ok((await sql<any[]>`SELECT id FROM collection_outcomes WHERE id=${r.id}`)[0]&&(await sql<any[]>`SELECT id FROM commitments WHERE id=${r.commitmentId}`)[0]);assert.ok((await repo.listAudit()).some(x=>x.resourceId===r.id));});
test("complaint remains recorded with responsibility; reactivation preserves state; opportunity creates work",async()=>{const due=new Date(Date.now()+86400000).toISOString(),c=await rep.capture(actor,"complaint",{customerId:customer,description:"issue",responsibleParty:"ops",followUpTitle:"follow",followUpDueAt:due},"x");assert.deepEqual((await sql<any[]>`SELECT status,responsible_party AS "owner" FROM complaints WHERE id=${c.id}`)[0],{status:"recorded",owner:"ops"});const inactive=(await sql<any[]>`SELECT id,is_active AS "active",classification,operational_status AS "status" FROM customers WHERE owner_employee_id=${actor.id} AND is_active=false LIMIT 1`)[0];if(inactive){await rep.reactivate(actor,inactive.id,{evidence:"r",title:"r",dueAt:due},"x");assert.deepEqual((await sql<any[]>`SELECT is_active AS "active",classification,operational_status AS "status" FROM customers WHERE id=${inactive.id}`)[0],{active:inactive.active,classification:inactive.classification,status:inactive.status})}const o=await rep.capture(actor,"opportunity",{customerId:customer,note:"cross sell",followUpTitle:"follow",followUpDueAt:due},"x");assert.ok((await sql<any[]>`SELECT commitment_id FROM opportunities WHERE id=${o.id}`)[0].commitment_id);});
test("activity and Close My Day derive persisted no-answer evidence and continuing work",async()=>{const id=await createCall();await tele.start(actor,id,"x");await tele.complete(actor,id,{outcome:"no_answer",evidence:"activity"},"x");assert.ok((await tele.activity(actor)).some(x=>x.evidence==="activity"&&x.outcome==="no_answer"));const d=await tele.day(actor);assert.ok(Number(d.openWork)>=1&&Number(d.noAnswer)>=1);});
test.after(async()=>{await sql.end()});
