import {randomUUID} from "node:crypto";
import postgres from "postgres";
import {PostgresIdentityRepository} from "../src/repository";
import {AuditService} from "../src/audit";
import {CustomerCommitmentService,type Actor} from "../src/customer-commitment";
import {RepresentativeService} from "../src/representative";
import {OrderLifecycleService} from "../src/order-lifecycle";
import {ComplaintLifecycleService} from "../src/complaint-lifecycle";
const url=process.env.DATABASE_URL;if(!url)throw new Error("DATABASE_URL is required.");
const sql=postgres(url),repo=new PostgresIdentityRepository(sql),audit=new AuditService(repo),commitments=new CustomerCommitmentService(sql,audit),representative=new RepresentativeService(sql,audit,commitments),orders=new OrderLifecycleService(sql,audit,commitments),complaints=new ComplaintLifecycleService(sql,audit,commitments);
const employee=await repo.findEmployeeByEmail("rep@local.test");if(!employee)throw new Error("Run Phase 0 bootstrap first.");const actor:Actor={id:employee.id,organizationId:employee.organizationId!,teamId:employee.teamId,role:"sales_representative"};
const customer=(await sql<any[]>`SELECT id FROM customers WHERE owner_employee_id=${actor.id} AND is_active=true ORDER BY created_at LIMIT 1`)[0];const product=(await sql<any[]>`SELECT id FROM products WHERE organization_id=${actor.organizationId} AND active=true LIMIT 1`)[0];if(!customer||!product)throw new Error("Run Phase 1 and 2 seeds first.");
async function order(label:string,review=false){return representative.createOrder(actor,{customerId:customer.id,productId:product.id,quantity:1,duplicateOverrideReason:`DEVELOPMENT/TEST Phase4 ${label}`,requiresCreditReview:review},`phase4-seed-${label}`)}
async function advance(id:string,to:string[],version=1){let v=version;for(const stage of to){await orders.transition(actor,id,{to:stage as any,evidence:`DEVELOPMENT/TEST evidence: ${stage}`,responsibleParty:"عمليات المبيعات",version:v},`phase4-seed-${stage}`);v++;}return v;}
const recorded=await order("recorded");const review=await order("credit-review",true);await advance(review.id,["credit_review"]);const blocked=await order("blocked");await orders.block(actor,blocked.id,{reason:"DEVELOPMENT/TEST credit confirmation",responsibleParty:"الائتمان",requiredNextAction:"تأكيد حد العميل",evidence:"DEVELOPMENT/TEST blocking evidence",followUpAt:new Date(Date.now()+86400000).toISOString(),createFollowUp:true,followUpIdempotencyKey:randomUUID(),version:1},"phase4-seed-blocked");const approved=await order("approved");await advance(approved.id,["approved"]);const preparation=await order("preparation");await advance(preparation.id,["approved","preparation"]);const deliveryPreparation=await order("delivery-preparation");await advance(deliveryPreparation.id,["approved","preparation","delivery_preparation"]);const delivered=await order("delivered");await advance(delivered.id,["approved","preparation","delivery_preparation","delivered"]);const closed=await order("closed");const closeVersion=await advance(closed.id,["approved","preparation","delivery_preparation","delivered"]);await orders.transition(actor,closed.id,{to:"closed",evidence:"DEVELOPMENT/TEST delivery closure evidence",responsibleParty:"عمليات التسليم",version:closeVersion},"phase4-seed-closed");
async function complaint(label:string){const id=randomUUID();await sql`INSERT INTO complaints(id,organization_id,customer_id,recorded_by_employee_id,classification,description,required_action) VALUES(${id},${actor.organizationId},${customer.id},${actor.id},'unclassified',${`DEVELOPMENT/TEST complaint ${label}`},'مراجعة الإجراء')`;return id;}
async function progress(id:string,steps:string[],version=1){let v=version;for(const to of steps){const input:any={to,evidence:`DEVELOPMENT/TEST complaint ${to}`,version:v,responsibleParty:"خدمة العملاء"};if(to==="classified")input.classification="quality";if(to==="corrective_action")input.correctiveAction="DEVELOPMENT/TEST corrective action";if(to==="follow_up"){input.createFollowUp=true;input.followUpTitle="DEVELOPMENT/TEST complaint follow-up";input.followUpAt=new Date(Date.now()+86400000).toISOString();input.followUpIdempotencyKey=randomUUID();}await complaints.transition(actor,id,input,`phase4-seed-complaint-${to}`);v++;}return v;}
await complaint("recorded");const classified=await complaint("classified");await progress(classified,["classified"]);const assigned=await complaint("assigned");await progress(assigned,["classified","assigned"]);const corrective=await complaint("corrective");await progress(corrective,["classified","assigned","corrective_action"]);const followUp=await complaint("follow-up");await progress(followUp,["classified","assigned","corrective_action","follow_up"]);const resolved=await complaint("resolved");await progress(resolved,["classified","assigned","corrective_action","follow_up","resolved"]);const complaintClosed=await complaint("closed");await progress(complaintClosed,["classified","assigned","corrective_action","follow_up","resolved","closed"]);
console.log(`Created DEVELOPMENT/TEST Phase 4 seed: orders ${recorded.id}, ${review.id}, ${blocked.id}, ${approved.id}, ${preparation.id}, ${deliveryPreparation.id}, ${delivered.id}, ${closed.id}; complaint lifecycle scenarios.`);await sql.end();
