import { randomUUID } from "node:crypto";
import postgres from "postgres";
import { hashPassword } from "../src/password";

const url=process.env.DATABASE_URL,password=process.env.SALES_BOOTSTRAP_PASSWORD;if(!url||!password)throw new Error("DATABASE_URL and SALES_BOOTSTRAP_PASSWORD are required.");
const sql=postgres(url); const rep=(await sql<any[]>`SELECT id,organization_id AS "organizationId",team_id AS "teamId" FROM employees WHERE email='rep@local.test'`)[0];if(!rep)throw new Error("Run Phase 0 bootstrap first.");
let employee=(await sql<any[]>`SELECT id FROM employees WHERE email='telesales@local.test'`)[0];if(!employee){const id=randomUUID();await sql`INSERT INTO employees(id,organization_id,team_id,email,display_name,password_hash,role) VALUES(${id},${rep.organizationId},${rep.teamId},'telesales@local.test','DEVELOPMENT/TEST telesales employee',${await hashPassword(password)},'telesales_employee')`;employee={id};}
const supervisorId=randomUUID();await sql`INSERT INTO employees(id,organization_id,team_id,email,display_name,password_hash,role) VALUES(${supervisorId},${rep.organizationId},${rep.teamId},${`supervisor-phase5-${supervisorId}@local.test`},'DEVELOPMENT/TEST supervisor',${await hashPassword(password)},'telesales_supervisor')`;
const call=(await sql<any[]>`SELECT id,customer_id AS "customerId" FROM telesales_calls WHERE owner_employee_id=${employee.id} ORDER BY created_at LIMIT 1`)[0];if(!call)throw new Error("Run Phase 3 seed first.");
async function exception(kind:string,status:"open"|"actioned"|"resolved",summary:string,severity="urgent"){const id=randomUUID();await sql`INSERT INTO supervisor_exceptions(id,organization_id,team_id,subject_employee_id,customer_id,source_type,source_id,kind,severity,summary,evidence,required_next_action,status,resolved_at,resolved_by_employee_id) VALUES(${id},${rep.organizationId},${rep.teamId},${employee.id},${call.customerId},'telesales_call',${call.id},${kind},${severity},${summary},'DEVELOPMENT/TEST source evidence','DEVELOPMENT/TEST required supervisory follow-up',${status},${status==='resolved'?new Date():null},${status==='resolved'?supervisorId:null})`;return id;}
const open=await exception("readiness_exception","open","DEVELOPMENT/TEST readiness exception");const actioned=await exception("overdue_follow_up","actioned","DEVELOPMENT/TEST actioned but still open","watch");const resolved=await exception("quality_exception","resolved","DEVELOPMENT/TEST genuinely resolved exception","normal");
await sql`INSERT INTO supervisor_actions(id,exception_id,organization_id,actor_employee_id,kind,evidence,follow_up_at,resolves_work) VALUES(${randomUUID()},${actioned},${rep.organizationId},${supervisorId},'escalate','DEVELOPMENT/TEST escalation evidence',now()+interval '1 day',false)`;
for(const [checkpoint,state] of [["morning","attention"],["midday","risk"],["end_of_day","attention"]] as const)await sql`INSERT INTO supervisor_checkpoints(id,organization_id,team_id,checkpoint,actor_employee_id,evidence,readiness_state) VALUES(${randomUUID()},${rep.organizationId},${rep.teamId},${checkpoint},${supervisorId},${`DEVELOPMENT/TEST ${checkpoint} checkpoint evidence`},${state})`;
await sql`INSERT INTO supervisor_quality_reviews(id,organization_id,team_id,reviewed_employee_id,source_type,source_id,evidence,result,observation,actor_employee_id) VALUES(${randomUUID()},${rep.organizationId},${rep.teamId},${employee.id},'telesales_call',${call.id},'DEVELOPMENT/TEST quality evidence','needs_improvement','DEVELOPMENT/TEST quality observation',${supervisorId})`;
await sql`INSERT INTO supervisor_coaching_records(id,organization_id,team_id,employee_id,source_type,source_id,topic,evidence,agreed_action,due_at,actor_employee_id) VALUES(${randomUUID()},${rep.organizationId},${rep.teamId},${employee.id},'telesales_call',${call.id},'DEVELOPMENT/TEST coaching topic','DEVELOPMENT/TEST coaching evidence','DEVELOPMENT/TEST agreed action',now()-interval '1 day',${supervisorId})`;
console.log(`Created DEVELOPMENT/TEST Phase 5 Supervisor seed: ${open}, ${actioned}, ${resolved}.`);await sql.end();
