import {expect,test}from"@playwright/test";
type Scenario={purpose:string;outcomes:string[];result?:string;next?:boolean;customer?:string};
async function fixture(page:any,s:Scenario={purpose:"collection",outcomes:["successful_contact","payment_promise","callback","no_answer"]}){let auth=false,state="queued",queue=[{id:"call-1",customerId:"c1",customerName:s.customer??"TEST Priority Customer",purpose:s.purpose,priorityReason:"TEST explainable priority reason",scheduledAt:"2026-08-22T09:00:00Z",state}];await page.route("**/api/**",async(r:any)=>{const p=new URL(r.request().url()).pathname,m=r.request().method(),send=(x:any,status=200)=>r.fulfill({status,contentType:"application/json",body:JSON.stringify(x)});if(p==="/api/auth/me")return auth?send({employee:{id:"tel",displayName:"TEST Telesales",role:"telesales_employee"},csrfToken:"csrf"}):send({},401);if(p==="/api/auth/login"){auth=true;return send({employee:{id:"tel",displayName:"TEST Telesales",role:"telesales_employee"},csrfToken:"csrf"})}if(p==="/api/telesales/queue")return send(queue);if(p==="/api/telesales/day")return send({noAnswer:3,escalations:1,openWork:1,tomorrowCarryover:1,callbacks:1});if(p==="/api/telesales/activity")return send([{id:"a1",customerName:"TEST Priority Customer",outcome:"no_answer",result:"escalated",evidence:"TEST operational evidence",at:"2026-08-29T09:00:00Z"}]);if(p==="/api/customers")return send([{id:"c1",name:"TEST Inactive Customer",classification:"follow_up",openCommitments:1,isActive:false}]);if(p==="/api/telesales/products")return send([{id:"p1",name:"TEST Product",referenceCode:"P1"}]);if(p==="/api/telesales/calls/call-1")return send({call:{...queue[0],state,contactName:"TEST Contact",phone:"010",operationalNotes:"TEST pre-call evidence"},attempts:[{outcome:"no_answer",result:"followup",evidence:"TEST previous attempt",attemptedAt:"2026-08-22T08:00:00Z"}],commitments:[{id:"cm1",title:"TEST Commitment",dueAt:"2026-08-22T10:00:00Z",status:"open"}],allowedOutcomes:s.outcomes});if(p==="/api/telesales/calls/call-1/start"){state="in_progress";return send({id:"call-1"})}if(p.startsWith("/api/telesales/calls/call-1/")&&p!=="/api/telesales/calls/call-1/complete")return send({id:"work-1",commitmentId:"cm1"},201);if(p==="/api/telesales/calls/call-1/complete"){queue=s.next?[{id:"call-2",customerId:"c1",customerName:"TEST Next Call",purpose:"routine",priorityReason:"TEST persisted retry",scheduledAt:"2026-08-22T10:00:00Z",state:"queued"}]:[];return send({id:"call-1",result:s.result??"followup",nextCallId:s.next?"call-2":null})}return send({},m==="POST"?201:200)});await page.goto("/login");await page.locator("input").nth(1).fill("password");await page.locator("form button").click();await expect(page).toHaveURL(/telesales/)}
async function openLive(page:any){await page.locator(".telesales-row").first().click();await expect(page.getByText("TEST pre-call evidence")).toBeVisible();await page.getByRole("button",{name:"بدء الاتصال"}).click();await expect(page.locator("select")).toBeVisible()}

test("opened call cannot trap My Work or Customers navigation",async({page})=>{
  await fixture(page);
  await page.locator(".artifact4-next-action").click();
  await expect(page.getByText("TEST pre-call evidence")).toBeVisible();
  await page.getByRole("button",{name:"عملي",exact:true}).click();
  await expect(page.getByText("ملخص التنفيذ المحفوظ")).toBeVisible();
  await expect(page.locator(".telesales-call")).toHaveCount(0);
  await page.getByRole("button",{name:"العملاء",exact:true}).click();
  await expect(page.getByText("عملاؤك")).toBeVisible();
  await expect(page.getByText("TEST Inactive Customer")).toBeVisible();
  await expect(page.locator(".telesales-call")).toHaveCount(0);
});
test("core journey renders dominant priority, pre-call evidence, live state, validation, consequence and refreshed next work",async({page})=>{await fixture(page,{purpose:"collection",outcomes:["no_answer"],next:true});await expect(page.locator("html")).toHaveAttribute("dir","rtl");await expect(page.getByText("TEST explainable priority reason").first()).toBeVisible();await openLive(page);await page.locator("input[type=checkbox]").first().check();await page.locator("select").selectOption("no_answer");await expect(page.getByRole("button",{name:"حفظ النتيجة"})).toBeDisabled();await page.locator("textarea").last().fill("TEST evidence");await page.getByRole("button",{name:"حفظ النتيجة"}).click();await expect(page.getByText("بين المكالمات")).toBeVisible();await expect(page.getByText("TEST Next Call").first()).toBeVisible()});
test("no-answer and escalation outcomes render separate operational consequence",async({page})=>{await fixture(page,{purpose:"routine",outcomes:["no_answer"],result:"escalated",next:false});await openLive(page);await page.locator("select").selectOption("no_answer");await page.locator("textarea").last().fill("third no answer");await page.getByRole("button",{name:"حفظ النتيجة"}).click();await expect(page.getByText(/التصعيد/)).toBeVisible();await expect(page.getByText("بين المكالمات")).toBeVisible()});
test("callback exposes due point and returns same-day next work",async({page})=>{await fixture(page,{purpose:"collection",outcomes:["callback"],next:true});await openLive(page);await page.locator("select").selectOption("callback");await expect(page.locator('input[type="datetime-local"]')).toBeVisible();await page.locator('input[type="datetime-local"]').fill("2026-08-22T10:00");await page.locator("textarea").last().fill("callback evidence");await page.getByRole("button",{name:"حفظ النتيجة"}).click();await expect(page.getByText("TEST Next Call").first()).toBeVisible()});
test("order capture is conditional and validates product and positive quantity",async({page})=>{await fixture(page,{purpose:"routine",outcomes:["successful_contact"],next:false});await openLive(page);await page.locator("select").selectOption("successful_contact");await expect(page.getByText("التقاط نتيجة التواصل")).toBeVisible();await page.getByRole("button",{name:"حفظ العمل الناتج"}).click();await expect(page.getByText(/اختر المنتج/)).toBeVisible();await page.locator("fieldset select").selectOption("p1");await page.locator('input[type="number"]').fill("2");await page.getByRole("button",{name:"حفظ العمل الناتج"}).click();await expect(page.getByText(/تم حفظ order/)).toBeVisible()});
test("payment promise form requires due point and exposes resulting commitment consequence",async({page})=>{await fixture(page,{purpose:"collection",outcomes:["payment_promise"],next:false});await openLive(page);await page.locator("select").selectOption("payment_promise");await page.getByRole("button",{name:"حفظ العمل الناتج"}).click();await expect(page.getByText(/المبلغ/)).toBeVisible();await page.locator('input[type="number"]').fill("100");await page.locator('input[type="datetime-local"]').fill("2026-08-23T10:00");await page.getByRole("button",{name:"حفظ العمل الناتج"}).click();await expect(page.getByText(/تم حفظ collection/)).toBeVisible()});
test("complaint capture requires explicit classification, responsibility, due point, and evidence",async({page})=>{await fixture(page,{purpose:"complaint_followup",outcomes:["complaint"]});await openLive(page);await page.locator("select").first().selectOption("complaint");await expect(page.getByText("التقاط نتيجة التواصل")).toBeVisible();await page.getByRole("button",{name:"حفظ العمل الناتج"}).click();await expect(page.getByText("تصنيف الشكوى والمسؤول والإجراء والموعد والدليل مطلوبة.")).toBeVisible();await page.locator("fieldset select").selectOption("delivery");await page.getByPlaceholder("الطرف المسؤول").fill("TEST logistics owner");await page.getByPlaceholder("الإجراء المطلوب").fill("TEST follow-up action");await page.getByLabel("موعد متابعة الشكوى").fill("2026-08-30T10:00");await page.getByPlaceholder("تفاصيل/دليل").fill("TEST complaint evidence");await page.getByRole("button",{name:"حفظ العمل الناتج"}).click();await expect(page.getByText(/مسجلة وليست محلولة/)).toBeVisible();});
test("opportunity capture requires canonical kind, due point, and evidence",async({page})=>{await fixture(page,{purpose:"opportunity",outcomes:["successful_contact"]});await openLive(page);await page.locator("select").first().selectOption("successful_contact");await page.getByRole("button",{name:"حفظ العمل الناتج"}).click();await expect(page.getByText("نوع الفرصة وموعد المتابعة والدليل مطلوبة.")).toBeVisible();await page.locator("fieldset select").first().selectOption("cross_sell");await page.getByLabel("موعد متابعة الفرصة").fill("2026-08-31T10:00");await page.getByPlaceholder("تفاصيل/دليل").fill("TEST opportunity evidence");await page.getByRole("button",{name:"حفظ العمل الناتج"}).click();await expect(page.getByText(/تم حفظ opportunity/)).toBeVisible();});
test("operational tabs render scoped customers, operational activity and Close My Day derivations",async({page})=>{await fixture(page);await page.getByRole("button",{name:"العملاء",exact:true}).click();await expect(page.getByText("TEST Inactive Customer")).toBeVisible();await page.getByRole("button",{name:"النشاط",exact:true}).click();await expect(page.getByText("تقويم نشاط المبيعات الهاتفية")).toBeVisible();await page.locator('.activity-calendar__day[aria-label*="1 أدلة محفوظة"]').click();await expect(page.locator(".activity-calendar__details")).toContainText("TEST operational evidence");await page.getByRole("button",{name:"عملي",exact:true}).click();for(const x of ["بدون إجابة","تصعيدات","عمل مفتوح","عمل محمول للغد"])await expect(page.getByText(x)).toBeVisible()});
