import type { ReactNode } from "react";
export type Attention = "normal" | "caution" | "urgent" | "success";
export function StatusLabel({ attention = "normal", children }: { attention?: Attention; children: ReactNode }) { return <span className={`ds-status ds-status--${attention}`}>{children}</span>; }
export function NextActionHero({ eyebrow, title, detail }: { eyebrow: string; title: string; detail: string }) { return <section className="ds-hero"><p>{eyebrow}</p><h1>{title}</h1><span>{detail}</span></section>; }
export function CommitmentRail({ children }: { children: ReactNode }) { return <ol className="ds-rail">{children}</ol>; }
export function CommitmentRailItem({ state = "normal", time, title, meta }: { state?: Attention; time: string; title: string; meta: string }) { return <li className="ds-rail__item"><span className={`ds-rail__node ds-rail__node--${state}`} /><div><time>{time}</time><strong>{title}</strong><p>{meta}</p></div></li>; }
export function LedgerRow({ label, detail, status }: { label: string; detail: string; status?: ReactNode }) { return <article className="ds-ledger-row"><div><strong>{label}</strong><p>{detail}</p></div>{status}</article>; }
export function StatePanel({ kind, title, detail, retry }: { kind: "loading" | "empty" | "error" | "denied"; title: string; detail: string; retry?: () => void }) { return <section className={`ds-state ds-state--${kind}`} aria-live={kind === "loading" ? "polite" : undefined}><strong>{title}</strong><p>{detail}</p>{retry && <button type="button" onClick={retry}>إعادة المحاولة</button>}</section>; }
export function LifecycleMiniRail() { return <ol className="ds-lifecycle" aria-label="المسار التشغيلي الداخلي للطلب">{[["مسجل", "success"], ["مراجعة الحسابات", "success"], ["معتمد", "normal"], ["التجهيز", "normal"], ["تجهيز التسليم", "normal"], ["تم التسليم", "normal"], ["مغلق", "normal"]].map(([label, state]) => <li key={label}><span className={`ds-lifecycle__node ds-lifecycle__node--${state}`} />{label}</li>)}</ol>; }
