import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { KeyboardTextarea } from "../../mobile";
import { completeVisit, representativeDay, startVisit, type SessionIdentity } from "../../lib/api";
import { CommitmentRail, CommitmentRailItem, LedgerRow, NextActionHero, StatePanel, StatusLabel } from "../../design-system/foundation";
const egp=(value:number)=>new Intl.NumberFormat("ar-EG",{style:"currency",currency:"EGP",maximumFractionDigits:0}).format(Number(value)||0);
export function RepresentativeWorkspace({session}:{session:SessionIdentity}) {
 const qc=useQueryClient(); const q=useQuery({queryKey:["rep-day"],queryFn:representativeDay}); const [selected,setSelected]=useState<string|null>(null); const [outcome,setOutcome]=useState(""); const [evidence,setEvidence]=useState(""); const [inspection,setInspection]=useState<string|null>(null);
 const refresh=()=>qc.invalidateQueries({queryKey:["rep-day"]});
 if(q.isLoading)return <StatePanel kind="loading" title="جارٍ تحميل يوم العمل" detail="يتم جلب السجل التشغيلي المحفوظ."/>;
 if(q.isError)return <StatePanel kind="error" title="تعذر تحميل يوم العمل" detail="تحقق من الاتصال ثم أعد المحاولة." retry={()=>q.refetch()}/>;
 const day=q.data!,current=day.visits.find(v=>v.id===selected),close=day.close;
 const ledger=(id:string,label:string,detail:string)=><section key={id}><button className="customer-core-row" onClick={()=>setInspection(inspection===id?null:id)}><LedgerRow label={label} detail={detail} status={<StatusLabel>{inspection===id?"إخفاء الدليل":"فحص الدليل"}</StatusLabel>}/></button>{inspection===id&&<div className="close-evidence"><p>{id==="visits"?"راجع سجلات الزيارات أعلاه؛ وهي المصدر نفسه لهذه النتيجة.":id==="commitments"?"راجع مسار الالتزامات المباشر أعلاه؛ وهو المصدر نفسه للعمل المحمول.":"هذا الإجمالي مشتق من سجلات اليوم المحفوظة، وليس من ملخص يدوي."}</p></div>}</section>;
 if(current)return <section className="rep-outcome"><button className="customer-back" onClick={()=>setSelected(null)}>رجوع إلى اليوم</button><NextActionHero eyebrow="تنفيذ زيارة" title={current.customerName} detail={current.purpose}/><label>ما الذي حدث؟<KeyboardTextarea value={outcome} onChange={e=>setOutcome(e.target.value)}/></label><label>الدليل أو النتيجة<KeyboardTextarea value={evidence} onChange={e=>setEvidence(e.target.value)}/></label><button className="production-primary" disabled={!outcome||!evidence} onClick={()=>completeVisit(current.id,session.csrfToken,{outcome,evidence}).then(()=>{setSelected(null);refresh()})}>حفظ النتيجة وإكمال الزيارة</button></section>;
 return <><NextActionHero eyebrow="استعداد الصباح" title={day.visits.find(v=>v.status!=="completed")?.purpose??"لا توجد زيارات معلقة"} detail="سجل الدليل، ثم تابع العمل الناتج من نفس السجل."/><h2>زيارات اليوم</h2>{day.visits.map(v=><article className="rep-visit" key={v.id}><LedgerRow label={v.customerName} detail={`${new Intl.DateTimeFormat("ar-EG",{timeStyle:"short"}).format(new Date(v.plannedAt))} · ${v.purpose}`} status={<StatusLabel>{v.status}</StatusLabel>}/>{v.status==="planned"&&<button className="production-primary" onClick={()=>startVisit(v.id,session.csrfToken).then(refresh)}>بدء الزيارة</button>}{v.status==="in_progress"&&<button className="production-primary" onClick={()=>setSelected(v.id)}>تنفيذ الزيارة</button>}</article>)}<h2>مسار الالتزامات المباشر</h2><CommitmentRail>{day.commitments.map(c=><CommitmentRailItem key={c.id} state={new Date(c.dueAt)<new Date()?"urgent":"normal"} time={new Intl.DateTimeFormat("ar-EG",{dateStyle:"short",timeStyle:"short"}).format(new Date(c.dueAt))} title={c.title} meta="التزام محفوظ · مسؤول التنفيذ: أنت"/>)}</CommitmentRail><h2>إغلاق يومي مشتق</h2>{ledger("visits","الزيارات والعملاء",`${close.plannedVisits} مخططة · ${close.completedVisits} مكتملة · ${close.customersVisited} عملاء تمت زيارتهم`)}{ledger("orders","الطلبات المسجلة",`${close.orders} طلبات · ${egp(close.orderValue)}`)}{ledger("collections","التحصيل",`${close.collections} عمليات · ${egp(close.collectedAmount)}`)}{ledger("promises","وعود السداد",`${close.paymentPromises} وعود · ${egp(close.promiseAmount)}`)}{ledger("complaints","الشكاوى والقضايا",`${close.complaints} شكاوى مسجلة — التسجيل لا يعني الحل`)}{ledger("opportunities","الفرص والبيع الإضافي",`${close.opportunities} فرص مسجلة`)}{ledger("observations","ملاحظات السوق",`${close.observations} أدلة سوق محفوظة`)}{ledger("reactivations","إعادة التنشيط",`${close.reactivations} متابعات لعملاء غير نشطين`)}{ledger("commitments","المتابعات والعمل المحمول",`${close.openFollowUps} التزامات مفتوحة · ${close.carriedForward} عمل محمول`)}<LedgerRow label="نتائج الزيارات" detail={day.visits.filter(v=>v.outcome).map(v=>v.outcome).join(" · ")||"لا توجد نتائج مكتملة بعد"}/></>;
}
