import { randomUUID } from "node:crypto";
import type { Sql } from "postgres";
import { AuditService } from "./audit";
import { CustomerCommitmentService, type Actor } from "./customer-commitment";

export class RepresentativeService {
  constructor(private readonly sql: Sql, private readonly audit: AuditService, private readonly commitments: CustomerCommitmentService) {}
  private async customer(actor: Actor, id: string) { const detail = await this.commitments.customerDetail(actor, id); if (!detail) throw Object.assign(new Error("Customer is not accessible."), { statusCode: 404 }); return detail.customer; }
  private followUp(input: any, sourceType: string, sourceId: string, title: string) { if (!input.followUpTitle && !input.followUpDueAt) return null; if (!input.followUpTitle || !input.followUpDueAt) throw Object.assign(new Error("Follow-up title and due point are required together."), { statusCode: 422 }); return { customerId: input.customerId, kind: "follow_up" as const, title: input.followUpTitle ?? title, dueAt: input.followUpDueAt, sourceType, sourceId, sourceEvidence: input.evidence ?? input.note ?? input.description ?? null, idempotencyKey: randomUUID() }; }
  async day(actor: Actor) {
    const visits=await this.sql<any[]>`SELECT v.id,v.customer_id AS "customerId",c.name AS "customerName",v.planned_at AS "plannedAt",v.purpose,v.status,v.outcome FROM visits v JOIN customers c ON c.id=v.customer_id WHERE v.representative_id=${actor.id} AND v.planned_at::date=current_date ORDER BY v.planned_at`;
    const commitments=await this.sql<any[]>`SELECT id,title,due_at AS "dueAt",status,urgency FROM commitments WHERE owner_employee_id=${actor.id} AND status='open' ORDER BY due_at`;
    const [close]=await this.sql<any[]>`SELECT (SELECT count(*)::int FROM visits WHERE representative_id=${actor.id} AND planned_at::date=current_date) AS "plannedVisits",(SELECT count(*)::int FROM visits WHERE representative_id=${actor.id} AND completed_at::date=current_date) AS "completedVisits",(SELECT count(DISTINCT customer_id)::int FROM visits WHERE representative_id=${actor.id} AND completed_at::date=current_date) AS "customersVisited",(SELECT count(*)::int FROM sales_orders WHERE recorded_by_employee_id=${actor.id} AND created_at::date=current_date) AS orders,(SELECT COALESCE(sum(oi.quantity*COALESCE(oi.unit_price,0)),0) FROM sales_orders o JOIN sales_order_items oi ON oi.order_id=o.id WHERE o.recorded_by_employee_id=${actor.id} AND o.created_at::date=current_date) AS "orderValue",(SELECT count(*)::int FROM collection_outcomes WHERE representative_id=${actor.id} AND created_at::date=current_date AND outcome IN ('collected','partial')) AS collections,(SELECT COALESCE(sum(amount_collected),0) FROM collection_outcomes WHERE representative_id=${actor.id} AND created_at::date=current_date) AS "collectedAmount",(SELECT count(*)::int FROM collection_outcomes WHERE representative_id=${actor.id} AND created_at::date=current_date AND outcome='promise') AS "paymentPromises",(SELECT COALESCE(sum(promise_amount),0) FROM collection_outcomes WHERE representative_id=${actor.id} AND created_at::date=current_date AND outcome='promise') AS "promiseAmount",(SELECT count(*)::int FROM complaints WHERE recorded_by_employee_id=${actor.id} AND created_at::date=current_date) AS complaints,(SELECT count(*)::int FROM opportunities WHERE owner_employee_id=${actor.id} AND created_at::date=current_date) AS opportunities,(SELECT count(*)::int FROM market_observations WHERE reported_by_employee_id=${actor.id} AND created_at::date=current_date) AS observations,(SELECT count(*)::int FROM commitments WHERE owner_employee_id=${actor.id} AND source_type='reactivation' AND created_at::date=current_date) AS reactivations,(SELECT count(*)::int FROM commitments WHERE owner_employee_id=${actor.id} AND status='open') AS "openFollowUps",(SELECT count(*)::int FROM commitments WHERE owner_employee_id=${actor.id} AND status='open' AND due_at<now()) AS "carriedForward"`;
    return { visits, commitments, close };
  }
  async products(actor: Actor) { return this.sql<any[]>`SELECT id,reference_code AS "referenceCode",name FROM products WHERE organization_id=${actor.organizationId} AND active=true`; }
  async createVisit(actor: Actor,input:any,correlationId:string) { await this.customer(actor,input.customerId);const id=randomUUID();await this.sql`INSERT INTO visits(id,organization_id,customer_id,representative_id,planned_at,purpose,idempotency_key) VALUES(${id},${actor.organizationId},${input.customerId},${actor.id},${new Date(input.plannedAt)},${input.purpose},${input.idempotencyKey})`;await this.audit.record({actorId:actor.id,action:"visit.planned",resourceType:"visit",resourceId:id,before:null,after:{},reason:null,correlationId});return{id}; }
  async startVisit(actor: Actor,id:string,correlationId:string) { const [row]=await this.sql<any[]>`UPDATE visits SET status='in_progress',started_at=now() WHERE id=${id} AND representative_id=${actor.id} AND status='planned' RETURNING id`;if(!row)throw Object.assign(new Error("Visit cannot be started."),{statusCode:409});await this.audit.record({actorId:actor.id,action:"visit.started",resourceType:"visit",resourceId:id,before:null,after:{},reason:null,correlationId});return row; }
  async completeVisit(actor: Actor,id:string,input:any,correlationId:string) { const visit=(await this.sql<any[]>`SELECT * FROM visits WHERE id=${id} AND representative_id=${actor.id}`)[0];if(!visit||visit.status!=="in_progress")throw Object.assign(new Error("Only an in-progress visit can be completed."),{statusCode:409});let commitmentId:string|null=null;await this.sql.begin(async tx=>{const followUp=this.followUp({...input,customerId:visit.customer_id},"visit",id,"Visit follow-up");if(followUp)commitmentId=(await this.commitments.createCommitmentInTransaction(tx,actor,followUp)).id;await tx`UPDATE visits SET status='completed',completed_at=now(),outcome=${input.outcome},evidence=${input.evidence},notes=${input.notes??null} WHERE id=${id}`;});await this.audit.record({actorId:actor.id,action:"visit.completed",resourceType:"visit",resourceId:id,before:{status:"in_progress"},after:{status:"completed",commitmentId},reason:null,correlationId});return{id,commitmentId}; }
  async createOrder(actor: Actor,input:any,correlationId:string) { await this.customer(actor,input.customerId);const product=(await this.sql<any[]>`SELECT id FROM products WHERE id=${input.productId} AND organization_id=${actor.organizationId} AND active=true`)[0];if(!product)throw Object.assign(new Error("Product is not available."),{statusCode:422});const duplicate=(await this.sql<any[]>`SELECT o.id FROM sales_orders o JOIN sales_order_items oi ON oi.order_id=o.id WHERE o.customer_id=${input.customerId} AND oi.product_id=${input.productId} AND o.created_at>now()-interval '24 hours' ORDER BY o.created_at DESC LIMIT 1`)[0];if(duplicate&&!input.duplicateOverrideReason)throw Object.assign(new Error("A recent order request for this customer and product already exists."),{statusCode:409});const id=randomUUID();await this.sql.begin(async tx=>{await tx`INSERT INTO sales_orders(id,organization_id,customer_id,visit_id,recorded_by_employee_id,request_note,duplicate_override_reason,requires_credit_review) VALUES(${id},${actor.organizationId},${input.customerId},${input.visitId??null},${actor.id},${input.requestNote??null},${input.duplicateOverrideReason??null},${input.requiresCreditReview??false})`;await tx`INSERT INTO sales_order_items(id,order_id,product_id,quantity,unit_price) VALUES(${randomUUID()},${id},${input.productId},${input.quantity},${input.unitPrice??null})`;});await this.audit.record({actorId:actor.id,action:"order.recorded",resourceType:"order",resourceId:id,before:null,after:{customerId:input.customerId,productId:input.productId,duplicateOverride:!!input.duplicateOverrideReason,requiresCreditReview:input.requiresCreditReview??false},reason:input.duplicateOverrideReason??null,correlationId});return{id,status:"recorded"}; }
  async reactivate(actor: Actor,id:string,input:any,correlationId:string) { const customer=await this.customer(actor,id);if(customer.isActive)throw Object.assign(new Error("Reactivation work is only for inactive customers."),{statusCode:409});const result=await this.commitments.createCommitment(actor,{customerId:id,kind:"follow_up",title:input.title,dueAt:input.dueAt,sourceType:"reactivation",sourceId:id,sourceEvidence:input.evidence,idempotencyKey:randomUUID()},correlationId);await this.audit.record({actorId:actor.id,action:"customer.reactivation_initiated",resourceType:"customer",resourceId:id,before:null,after:{isActive:false},reason:input.evidence,correlationId});return{commitmentId:result.id,isActive:false}; }
  async capture(actor: Actor,type:string,input:any,correlationId:string) {
    await this.customer(actor,input.customerId);const id=randomUUID();
    if(type==="collection") {
      if(!input.outcome||!input.evidence)throw Object.assign(new Error("Collection outcome and evidence are required."),{statusCode:422});
      if(input.outcome==="promise") { if(!input.promiseAmount||!input.promiseDueAt)throw Object.assign(new Error("Promise amount and due point are required."),{statusCode:422});let commitmentId:string|null=null;await this.sql.begin(async tx=>{commitmentId=(await this.commitments.createCommitmentInTransaction(tx,actor,{customerId:input.customerId,kind:"follow_up",title:input.followUpTitle??"Payment promise follow-up",dueAt:input.followUpDueAt??input.promiseDueAt,sourceType:"collection",sourceId:id,sourceEvidence:input.evidence,idempotencyKey:randomUUID()})).id;await tx`INSERT INTO collection_outcomes(id,organization_id,customer_id,visit_id,representative_id,outcome,amount_collected,promise_amount,promise_due_at,evidence,commitment_id) VALUES(${id},${actor.organizationId},${input.customerId},${input.visitId??null},${actor.id},'promise',0,${input.promiseAmount},${new Date(input.promiseDueAt)},${input.evidence},${commitmentId})`;await this.audit.recordInTransaction(tx,{actorId:actor.id,action:"collection.created",resourceType:"collection",resourceId:id,before:null,after:{customerId:input.customerId,commitmentId},reason:null,correlationId});await this.audit.recordInTransaction(tx,{actorId:actor.id,action:"commitment.created",resourceType:"commitment",resourceId:commitmentId!,before:null,after:{customerId:input.customerId,sourceType:"collection"},reason:null,correlationId});});return{id,commitmentId}; }
      await this.sql`INSERT INTO collection_outcomes(id,organization_id,customer_id,visit_id,representative_id,outcome,amount_collected,promise_amount,promise_due_at,evidence) VALUES(${id},${actor.organizationId},${input.customerId},${input.visitId??null},${actor.id},${input.outcome},${input.amountCollected??0},null,null,${input.evidence})`;await this.audit.record({actorId:actor.id,action:"collection.created",resourceType:"collection",resourceId:id,before:null,after:{customerId:input.customerId},reason:null,correlationId});return{id,commitmentId:null};
    }
    const followUp=this.followUp(input,type,id,`${type} follow-up`);let commitmentId:string|null=null;await this.sql.begin(async tx=>{if(followUp)commitmentId=(await this.commitments.createCommitmentInTransaction(tx,actor,followUp)).id;if(type==="complaint")await tx`INSERT INTO complaints(id,organization_id,customer_id,visit_id,recorded_by_employee_id,classification,description,responsible_party,required_action,follow_up_at,commitment_id) VALUES(${id},${actor.organizationId},${input.customerId},${input.visitId??null},${actor.id},${input.classification??"general"},${input.description??input.note??"Recorded complaint"},${input.responsibleParty??null},${input.requiredAction??null},${input.followUpDueAt??null},${commitmentId})`;else if(type==="opportunity")await tx`INSERT INTO opportunities(id,organization_id,customer_id,visit_id,owner_employee_id,kind,product_reference,note,commitment_id) VALUES(${id},${actor.organizationId},${input.customerId},${input.visitId??null},${actor.id},${input.kind??"general"},${input.productReference??null},${input.note??"Recorded opportunity"},${commitmentId})`;else if(type==="observation")await tx`INSERT INTO market_observations(id,organization_id,customer_id,visit_id,reported_by_employee_id,competitor,product_reference,competitor_price,offer,observation_type,note) VALUES(${id},${actor.organizationId},${input.customerId},${input.visitId??null},${actor.id},${input.competitor??null},${input.productReference??null},${input.competitorPrice??null},${input.offer??null},${input.observationType??"general"},${input.note??"Recorded observation"})`;else throw Object.assign(new Error("Unsupported capture type."),{statusCode:422});});await this.audit.record({actorId:actor.id,action:`${type}.created`,resourceType:type,resourceId:id,before:null,after:{customerId:input.customerId,commitmentId},reason:null,correlationId});return{id,commitmentId};
  }
}
