import { randomUUID } from "node:crypto";
import type { Sql } from "postgres";
import { AuditService } from "./audit";
import { CustomerCommitmentService, type Actor } from "./customer-commitment";

type ActionKind = "acknowledge" | "escalate" | "reassign" | "follow_up" | "resolve";
const open = (status: string) => status !== "resolved";

export class SupervisorService {
  constructor(private readonly sql: Sql, private readonly audit: AuditService, private readonly commitments: CustomerCommitmentService) {}
  private deny(message: string, statusCode = 422): never { throw Object.assign(new Error(message), { statusCode }); }
  private async guard(actor: Actor) { if (actor.role !== "telesales_supervisor" || !actor.teamId) this.deny("Telesales Supervisor role required.", 403); const employee=(await this.sql<any[]>`SELECT id FROM employees WHERE id=${actor.id} AND organization_id=${actor.organizationId} AND team_id=${actor.teamId} AND role='telesales_supervisor' AND active=true`)[0];if(!employee)this.deny("Supervisor team scope is not authorized.",403); }
  private async exception(actor: Actor, id: string) {
    await this.guard(actor);
    const row = (await this.sql<any[]>`SELECT * FROM supervisor_exceptions WHERE id=${id} AND organization_id=${actor.organizationId} AND team_id=${actor.teamId}`)[0];
    if (!row) this.deny("Supervisor exception is not accessible.", 404);
    return row;
  }
  async workspace(actor: Actor) {
    await this.guard(actor);
    const team = await this.sql<any[]>`SELECT e.id,e.display_name AS "displayName",count(c.id) FILTER (WHERE c.state='queued' AND c.scheduled_at::date=current_date)::int AS "queuedCalls",count(c.id) FILTER (WHERE c.completed_at::date=current_date)::int AS "completedCalls" FROM employees e LEFT JOIN telesales_calls c ON c.owner_employee_id=e.id WHERE e.organization_id=${actor.organizationId} AND e.team_id=${actor.teamId} AND e.role='telesales_employee' GROUP BY e.id,e.display_name ORDER BY e.display_name`;
    const exceptions = await this.sql<any[]>`SELECT x.id,x.kind,x.severity,x.summary,x.evidence,x.required_next_action AS "requiredNextAction",x.status,x.version,x.source_type AS "sourceType",x.source_id AS "sourceId",x.created_at AS "createdAt",x.resolved_at AS "resolvedAt",e.display_name AS "employeeName",c.name AS "customerName",a.kind AS "priorAction",a.evidence AS "priorActionEvidence",a.follow_up_at AS "followUpAt",actor.display_name AS "actionActorName",a.resulting_commitment_id AS "resultingCommitmentId" FROM supervisor_exceptions x LEFT JOIN employees e ON e.id=x.subject_employee_id LEFT JOIN customers c ON c.id=x.customer_id LEFT JOIN LATERAL (SELECT * FROM supervisor_actions WHERE exception_id=x.id ORDER BY created_at DESC LIMIT 1) a ON true LEFT JOIN employees actor ON actor.id=a.actor_employee_id WHERE x.organization_id=${actor.organizationId} AND x.team_id=${actor.teamId} ORDER BY CASE x.status WHEN 'open' THEN 0 WHEN 'actioned' THEN 1 ELSE 2 END,CASE x.severity WHEN 'urgent' THEN 0 WHEN 'watch' THEN 1 ELSE 2 END,x.created_at DESC`;
    const checkpoints = await this.sql<any[]>`SELECT DISTINCT ON (checkpoint) checkpoint,evidence,readiness_state AS "readinessState",created_at AS "at" FROM supervisor_checkpoints WHERE organization_id=${actor.organizationId} AND team_id=${actor.teamId} ORDER BY checkpoint,created_at DESC`;
    const quality = await this.sql<any[]>`SELECT q.id,q.source_type AS "sourceType",q.source_id AS "sourceId",q.evidence,q.result,q.observation,q.created_at AS "at",e.display_name AS "employeeName" FROM supervisor_quality_reviews q JOIN employees e ON e.id=q.reviewed_employee_id WHERE q.organization_id=${actor.organizationId} AND q.team_id=${actor.teamId} ORDER BY q.created_at DESC LIMIT 10`;
    const coaching = await this.sql<any[]>`SELECT c.id,c.topic,c.evidence,c.agreed_action AS "agreedAction",c.due_at AS "dueAt",c.status,c.version,e.display_name AS "employeeName",c.source_type AS "sourceType",c.source_id AS "sourceId" FROM supervisor_coaching_records c JOIN employees e ON e.id=c.employee_id WHERE c.organization_id=${actor.organizationId} AND c.team_id=${actor.teamId} ORDER BY c.created_at DESC LIMIT 10`;
    return { team, exceptions: exceptions.map((x) => ({ ...x, resultingCommitment: x.resultingCommitmentId ? { id: x.resultingCommitmentId } : undefined, operationallyOpen: open(x.status) })), checkpoints, quality, coaching };
  }
  async recordCheckpoint(actor: Actor, input: { checkpoint: "morning" | "midday" | "end_of_day"; evidence: string; readinessState: "ready" | "attention" | "risk" }, correlationId: string) {
    await this.guard(actor); const id = randomUUID();
    await this.sql.begin(async tx => { await tx`INSERT INTO supervisor_checkpoints(id,organization_id,team_id,checkpoint,actor_employee_id,evidence,readiness_state) VALUES(${id},${actor.organizationId},${actor.teamId},${input.checkpoint},${actor.id},${input.evidence},${input.readinessState})`; await this.audit.recordInTransaction(tx,{actorId:actor.id,action:"supervisor.checkpoint_recorded",resourceType:"supervisor_checkpoint",resourceId:id,before:null,after:input,reason:input.evidence,correlationId}); }); return { id };
  }
  async action(actor: Actor, id: string, input: { kind: ActionKind; evidence: string; followUpAt?: string; followUpTitle?: string; ownerEmployeeId?: string; version: number; idempotencyKey?: string }, correlationId: string) {
    const exception = await this.exception(actor, id); const resolves = input.kind === "resolve";
    if (exception.status === "resolved" || !input.evidence || (resolves && !input.evidence) || (["follow_up", "reassign"] as string[]).includes(input.kind) && !input.followUpAt) this.deny("Invalid supervisor action.");
    if (input.kind === "reassign" && !input.ownerEmployeeId) this.deny("A responsible employee is required.");
    return this.sql.begin(async tx => {
      if(input.kind==="reassign"){const assignee=(await tx<any[]>`SELECT id FROM employees WHERE id=${input.ownerEmployeeId!} AND organization_id=${actor.organizationId} AND team_id=${actor.teamId} AND role='telesales_employee' AND active=true`)[0];if(!assignee)this.deny("Reassignment target is not in the supervisor team.",403);}
      const updated = (await tx<any[]>`UPDATE supervisor_exceptions SET status=${resolves ? "resolved" : "actioned"},resolved_at=${resolves ? new Date() : null},resolved_by_employee_id=${resolves ? actor.id : null},subject_employee_id=${input.kind === "reassign" ? input.ownerEmployeeId! : exception.subject_employee_id},version=version+1,updated_at=now() WHERE id=${id} AND version=${input.version} RETURNING version`)[0];
      if (!updated) this.deny("Exception was updated by another user.", 409);
      let commitmentId: string | null = null;
      if (input.followUpAt) {
        const customerId = exception.customer_id ?? (await tx<any[]>`SELECT customer_id FROM telesales_calls WHERE id=${exception.source_id}`)[0]?.customer_id;
        if (!customerId) this.deny("Source work has no customer for follow-up.");
        const commitment = await this.commitments.createCommitmentInTransaction(tx, actor, { customerId, ownerEmployeeId: input.ownerEmployeeId, kind: "follow_up", title: input.followUpTitle ?? exception.required_next_action, dueAt: input.followUpAt, sourceType: "supervisor_exception", sourceId: id, sourceEvidence: input.evidence, idempotencyKey: input.idempotencyKey ?? randomUUID() }); commitmentId = commitment.id;
      }
      const actionId = randomUUID(); await tx`INSERT INTO supervisor_actions(id,exception_id,organization_id,actor_employee_id,kind,evidence,follow_up_at,resulting_commitment_id,resolves_work) VALUES(${actionId},${id},${actor.organizationId},${actor.id},${input.kind},${input.evidence},${input.followUpAt ? new Date(input.followUpAt) : null},${commitmentId},${resolves})`;
      await this.audit.recordInTransaction(tx,{actorId:actor.id,action:"supervisor.exception_action",resourceType:"supervisor_exception",resourceId:id,before:{status:exception.status},after:{kind:input.kind,status:resolves?"resolved":"actioned",operationallyOpen:!resolves,commitmentId},reason:input.evidence,correlationId}); return { id, actionId, commitmentId, status: resolves ? "resolved" : "actioned", operationallyOpen: !resolves, version: updated.version };
    });
  }
  async qualityReview(actor: Actor, input: { employeeId: string; sourceType: string; sourceId: string; evidence: string; result: "ready" | "needs_improvement"; observation: string }, correlationId: string) { await this.guard(actor); const id=randomUUID(); await this.sql.begin(async tx=>{const employee=(await tx<any[]>`SELECT id FROM employees WHERE id=${input.employeeId} AND team_id=${actor.teamId} AND role='telesales_employee'`)[0];if(!employee)this.deny("Employee is not in the supervisor team.",404);await tx`INSERT INTO supervisor_quality_reviews(id,organization_id,team_id,reviewed_employee_id,source_type,source_id,evidence,result,observation,actor_employee_id) VALUES(${id},${actor.organizationId},${actor.teamId},${input.employeeId},${input.sourceType},${input.sourceId},${input.evidence},${input.result},${input.observation},${actor.id})`;await this.audit.recordInTransaction(tx,{actorId:actor.id,action:"supervisor.quality_review",resourceType:"supervisor_quality_review",resourceId:id,before:null,after:input,reason:input.evidence,correlationId});});return{id}; }
  async coach(actor: Actor, input: { employeeId: string; sourceType: string; sourceId: string; topic: string; evidence: string; agreedAction: string; dueAt?: string; createFollowUp?: boolean; idempotencyKey?: string }, correlationId: string) { await this.guard(actor); if(input.createFollowUp&&!input.dueAt)this.deny("A coaching follow-up due point is required."); return this.sql.begin(async tx=>{const employee=(await tx<any[]>`SELECT id FROM employees WHERE id=${input.employeeId} AND team_id=${actor.teamId} AND role='telesales_employee'`)[0];if(!employee)this.deny("Employee is not in the supervisor team.",404);const id=randomUUID();let commitmentId:string|null=null;if(input.createFollowUp){const source=(await tx<any[]>`SELECT customer_id FROM telesales_calls WHERE id=${input.sourceId}`)[0];if(!source)this.deny("Coaching source must be customer-linked call work.");const c=await this.commitments.createCommitmentInTransaction(tx,actor,{customerId:source.customer_id,ownerEmployeeId:input.employeeId,kind:"internal",title:input.agreedAction,dueAt:input.dueAt!,sourceType:"supervisor_coaching",sourceId:id,sourceEvidence:input.evidence,idempotencyKey:input.idempotencyKey??randomUUID()});commitmentId=c.id;}await tx`INSERT INTO supervisor_coaching_records(id,organization_id,team_id,employee_id,source_type,source_id,topic,evidence,agreed_action,due_at,resulting_commitment_id,actor_employee_id) VALUES(${id},${actor.organizationId},${actor.teamId},${input.employeeId},${input.sourceType},${input.sourceId},${input.topic},${input.evidence},${input.agreedAction},${input.dueAt?new Date(input.dueAt):null},${commitmentId},${actor.id})`;await this.audit.recordInTransaction(tx,{actorId:actor.id,action:"supervisor.coaching_recorded",resourceType:"supervisor_coaching",resourceId:id,before:null,after:{...input,commitmentId,operationallyOpen:true},reason:input.evidence,correlationId});return{id,commitmentId,operationallyOpen:true};}); }
}
