import { useState } from "react";
import "./supervisor.css";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { KeyboardTextarea } from "../../mobile";
import { CommitmentRail, CommitmentRailItem, LedgerRow, NextActionHero, StatePanel, StatusLabel } from "../../design-system/foundation";
import { supervisorAction, supervisorCheckpoint, supervisorCoaching, supervisorQuality, supervisorWorkspace, type SessionIdentity } from "../../lib/api";

const label: Record<string, string> = { morning: "الصباح", midday: "منتصف اليوم", end_of_day: "نهاية اليوم", open: "مفتوح", actioned: "تم إجراء تدخل — العمل مستمر", resolved: "تم الحل", acknowledge: "إقرار", escalate: "تصعيد", reassign: "إعادة إسناد", follow_up: "إنشاء متابعة", resolve: "حل فعلي", ready: "جاهز", attention: "انتباه", risk: "مخاطرة", needs_improvement: "يحتاج تحسين" };
const format = (value?: string) => value ? new Intl.DateTimeFormat("ar-EG", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)) : "—";
export function SupervisorWorkspace({ session }: { session: SessionIdentity }) {
  const client = useQueryClient(); const [selected, setSelected] = useState<string | null>(null); const [evidence, setEvidence] = useState(""); const [message, setMessage] = useState<string | null>(null);
  const data = useQuery({ queryKey: ["supervisor"], queryFn: supervisorWorkspace }); const refresh = () => client.invalidateQueries({ queryKey: ["supervisor"] });
  const write = useMutation({ mutationFn: async ({ type, body, id }: { type: string; body: Record<string, unknown>; id?: string }) => type === "action" ? supervisorAction(id!, session.csrfToken, body) : type === "checkpoint" ? supervisorCheckpoint(session.csrfToken, body) : type === "quality" ? supervisorQuality(session.csrfToken, body) : supervisorCoaching(session.csrfToken, body), onSuccess: () => { setEvidence(""); setMessage("تم حفظ الدليل التشغيلي وتحديث العرض."); refresh(); }, onError: (error) => setMessage(error instanceof Error ? error.message : "تعذر حفظ الإجراء.") });
  if (data.isLoading) return <StatePanel kind="loading" title="جارٍ تحميل إشراف الفريق" detail="يتم جلب الجاهزية والاستثناءات والأدلة." />;
  if (data.isError) return <StatePanel kind="error" title="تعذر تحميل الإشراف" detail="أعد المحاولة للوصول إلى أدلة الفريق." retry={() => data.refetch()} />;
  const workspace = data.data!; const exception = workspace.exceptions.find(x => x.id === selected) ?? workspace.exceptions[0]; const teamMember = workspace.team[0];
  const act = (kind: "escalate" | "follow_up" | "resolve") => { if (!exception || evidence.trim().length < 2) return setMessage("يلزم تسجيل دليل الإجراء."); write.mutate({ type: "action", id: exception.id, body: { kind, evidence, version: exception.version, ...(kind === "follow_up" ? { followUpAt: new Date(Date.now() + 86_400_000).toISOString(), followUpTitle: exception.requiredNextAction } : {}) } }); };
  return <section className="supervisor-workspace" aria-label="مساحة مشرف المبيعات الهاتفية">
    <NextActionHero eyebrow="إشراف المبيعات الهاتفية" title={workspace.exceptions.find(x => x.operationallyOpen)?.summary ?? "الفريق على المسار الصحيح"} detail="الأدلة أولاً؛ تسجيل التدخل لا يعني أن العمل قد حُل." />
    {message && <StatePanel kind="error" title="حالة الإجراء" detail={message} retry={() => setMessage(null)} />}
    <section><h2>نقاط التحقق الثلاث</h2><div className="supervisor-tabs">{["morning", "midday", "end_of_day"].map(kind => { const point = workspace.checkpoints.find(x => x.checkpoint === kind); return <button key={kind} onClick={() => write.mutate({ type: "checkpoint", body: { checkpoint: kind, evidence: `دليل ${label[kind]} — راجع الاستثناءات المفتوحة`, readinessState: workspace.exceptions.some(x => x.operationallyOpen && x.severity === "urgent") ? "risk" : "attention" } })}>{point ? `${label[kind]}: ${label[point.readinessState]}` : `تسجيل ${label[kind]}`}</button>; })}</div>{workspace.checkpoints.map(x => <LedgerRow key={x.checkpoint} label={label[x.checkpoint]} detail={x.evidence} status={<StatusLabel attention={x.readinessState === "risk" ? "urgent" : "caution"}>{label[x.readinessState]}</StatusLabel>} />)}</section>
    <section><h2>طابور الاستثناءات</h2>{workspace.exceptions.length === 0 ? <StatePanel kind="empty" title="لا توجد استثناءات" detail="لا يوجد عمل فريق يحتاج تدخلاً." /> : workspace.exceptions.map(x => <button key={x.id} className={`supervisor-exception ${exception?.id === x.id ? "selected" : ""}`} onClick={() => setSelected(x.id)}><StatusLabel attention={x.status === "resolved" ? "success" : x.severity === "urgent" ? "urgent" : "caution"}>{label[x.status]}</StatusLabel><strong>{x.summary}</strong><span>{x.employeeName ?? "فريق المبيعات"} · {x.customerName ?? "عمل تشغيلي"}</span>{x.priorAction && <small>إجراء سابق: {x.priorAction} — {x.operationallyOpen ? "العمل ما زال مفتوحاً" : "تم الحل"}</small>}</button>)}</section>
    {exception && <section className="supervisor-detail"><h2>دليل الاستثناء والإجراء التالي</h2><p>{exception.evidence}</p><p>التالي: {exception.requiredNextAction}</p><StatusLabel attention={exception.operationallyOpen ? "caution" : "success"}>{exception.operationallyOpen ? "مفتوح تشغيلياً" : "محلول فعلياً"}</StatusLabel>{exception.priorAction && <><LedgerRow label={`تدخل المشرف: ${label[exception.priorAction] ?? exception.priorAction}`} detail={`الدليل: ${exception.priorActionEvidence ?? "—"} · المسؤول: ${exception.actionActorName ?? "مسؤول مسجل"}`} status={<StatusLabel attention={exception.operationallyOpen ? "caution" : "success"}>{exception.operationallyOpen ? "العمل مستمر" : "تم الحل"}</StatusLabel>} />{exception.followUpAt && <LedgerRow label="موعد المتابعة الناتجة" detail={format(exception.followUpAt)} />}{exception.resultingCommitment && <><h3>التزام متابعة ناتج</h3><CommitmentRail><CommitmentRailItem state="caution" time={format(exception.followUpAt)} title="التزام متابعة ناتج محفوظ" meta={`معرّف الالتزام: ${exception.resultingCommitment.id} · مرتبط بهذا الاستثناء · العمل ما زال مفتوحاً`} /></CommitmentRail></>}</>}{exception.operationallyOpen && <><label>دليل تدخل المشرف<KeyboardTextarea value={evidence} onChange={event => setEvidence(event.target.value)} /></label><div className="supervisor-actions"><button className="production-secondary" onClick={() => act("escalate")}>تصعيد</button><button className="production-secondary" onClick={() => act("follow_up")}>إنشاء متابعة</button><button className="production-primary" onClick={() => act("resolve")}>تسجيل حل فعلي</button></div></>}</section>}
    <section><h2>تنفيذ الفريق</h2>{workspace.team.map(employee => <LedgerRow key={employee.id} label={employee.displayName} detail={`${employee.completedCalls} مكتملة · ${employee.queuedCalls} في الطابور`} status={<StatusLabel attention={employee.queuedCalls ? "caution" : "normal"}>{employee.queuedCalls ? "يحتاج متابعة" : "جاهز"}</StatusLabel>} />)}</section>
    <section><h2>مراجعة الجودة والتدريب</h2>{workspace.quality.map(review => <LedgerRow key={review.id} label={review.employeeName} detail={`${review.evidence} · ${review.observation}`} status={<StatusLabel attention={review.result === "needs_improvement" ? "caution" : "normal"}>{label[review.result]}</StatusLabel>} />)}{workspace.coaching.map(record => <CommitmentRail key={record.id}><CommitmentRailItem state={record.status === "open" ? "caution" : "normal"} time={record.dueAt ? new Intl.DateTimeFormat("ar-EG", { dateStyle: "short" }).format(new Date(record.dueAt)) : "بدون موعد"} title={`${record.employeeName} · ${record.topic}`} meta={`${record.evidence} · ${record.agreedAction} · ${label[record.status] ?? record.status}`} /></CommitmentRail>)}{teamMember && exception && <div className="supervisor-actions"><button className="production-secondary" onClick={() => write.mutate({ type: "quality", body: { employeeId: teamMember.id, sourceType: "telesales_call", sourceId: exception.sourceId, evidence: "دليل مراجعة جودة المشرف", result: "needs_improvement", observation: "توثيق النتيجة والمتابعة يحتاج تحسينا" } })}>تسجيل مراجعة جودة</button><button className="production-secondary" onClick={() => write.mutate({ type: "coaching", body: { employeeId: teamMember.id, sourceType: "telesales_call", sourceId: exception.sourceId, topic: "وضوح النتيجة والمتابعة", evidence: "دليل تدريب المشرف", agreedAction: "تأكيد النتيجة قبل إنهاء المكالمة", dueAt: new Date(Date.now() + 86_400_000).toISOString(), createFollowUp: true } })}>تسجيل تدريب ومتابعة</button></div>}</section>
  </section>;
}
