import { useEffect, useState, type ReactNode } from "react";
import "./production.css";
import { BrowserRouter, Navigate, NavLink, Route, Routes, useNavigate } from "react-router";
import { KeyboardInput, MobileScroll } from "../mobile";
import { NextActionHero, StatePanel, StatusLabel } from "../design-system/foundation";
import { getSession, login, type SessionIdentity } from "../lib/api";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { CustomerOperatingFile, CustomerRegister } from "../features/customers/CustomerCore";
import { RepresentativeWorkspace } from "../features/representative/RepresentativeWorkspace";
import { TelesalesWorkspace } from "../features/telesales/TelesalesWorkspace";
import { SupervisorWorkspace } from "../features/supervisor/SupervisorWorkspace";
import { ManagerWorkspace } from "../features/manager/ManagerWorkspace";

const roles = [["sales-representative", "مندوب مبيعات", "sales_representative"], ["telesales", "موظف مبيعات هاتفية", "telesales_employee"], ["supervisor", "مشرف مبيعات هاتفية", "telesales_supervisor"], ["manager", "مدير مبيعات", "sales_manager"]] as const;
type AuthState = { status: "checking" } | { status: "anonymous" } | { status: "authenticated"; session: SessionIdentity };
function LoginRoute({ onLogin }: { onLogin: (session: SessionIdentity) => void }) { const navigate=useNavigate(),[email,setEmail]=useState("rep@local.test"),[password,setPassword]=useState(""),[error,setError]=useState<string|null>(null),[saving,setSaving]=useState(false);return <MobileScroll className="production-screen"><main className="production-login"><NextActionHero eyebrow="منظومة المبيعات" title="تسجيل الدخول" detail="الوصول محمي حسب الدور والنطاق التشغيلي."/><form onSubmit={async e=>{e.preventDefault();setSaving(true);setError(null);try{const session=await login(email,password);onLogin(session);navigate(`/app/${roles.find(([, ,r])=>r===session.employee.role)?.[0]??"sales-representative"}`,{replace:true});}catch(cause){setError(cause instanceof Error?cause.message:"تعذر تسجيل الدخول.");}finally{setSaving(false);}}}><label>البريد الإلكتروني<KeyboardInput value={email} onChange={e=>setEmail(e.target.value)}/></label><label>كلمة المرور<KeyboardInput type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<StatePanel kind="error" title="تعذر تسجيل الدخول" detail={error}/>}<button className="production-primary" disabled={saving}>{saving?"جارٍ التحقق…":"تسجيل الدخول"}</button></form></main></MobileScroll>;}
function RoleWorkspace({role,session}:{role:string;session:SessionIdentity}){const[customerId,setCustomerId]=useState<string|null>(null);const r=session.employee.role;return <div className="production-app-shell"><header className="production-appbar"><span className="production-kicker">منظومة المبيعات</span><strong>{role}</strong><StatusLabel>{session.employee.displayName}</StatusLabel></header><MobileScroll className="production-screen"><main className="production-content">{customerId?<CustomerOperatingFile id={customerId} onBack={()=>setCustomerId(null)}/>:r==="sales_representative"?<><RepresentativeWorkspace session={session}/><CustomerRegister onOpen={setCustomerId}/></>:r==="telesales_employee"?<TelesalesWorkspace session={session} onCustomer={setCustomerId}/>:r==="telesales_supervisor"?<SupervisorWorkspace session={session}/>:r==="sales_manager"?<ManagerWorkspace session={session}/>:<StatePanel kind="empty" title="مسار الدور مهيأ" detail="لا توجد وظائف تشغيلية لهذا الدور."/>}</main></MobileScroll><nav className="production-nav" aria-label="أدوار التطبيق">{roles.map(([path,label])=><NavLink key={path} to={`/app/${path}`}>{label}</NavLink>)}</nav></div>;}
function Guard({state,role,children}:{state:AuthState;role:string;children:ReactNode}){if(state.status==="checking")return <StatePanel kind="loading" title="جارٍ التحقق من الجلسة" detail="يتم تحميل الوصول المصرح به."/>;if(state.status==="anonymous")return <Navigate to="/login" replace/>;if(state.session.employee.role!==role)return <StatePanel kind="denied" title="غير مصرح" detail="لا تملك صلاحية الوصول إلى مساحة هذا الدور."/>;return children;}
function AppRoutes({state,onLogin}:{state:AuthState;onLogin:(session:SessionIdentity)=>void}){const destination=state.status==="authenticated"?(roles.find(([, ,r])=>r===state.session.employee.role)?.[0]??"sales-representative"):"sales-representative";return <Routes><Route path="/login" element={state.status==="authenticated"?<Navigate to={`/app/${destination}`} replace/>:<LoginRoute onLogin={onLogin}/>}/>{roles.map(([path,label,role])=><Route key={path} path={`/app/${path}`} element={<Guard state={state} role={role}><RoleWorkspace role={label} session={state.status==="authenticated"?state.session:{employee:{id:"",displayName:"",role:""},csrfToken:""}}/></Guard>}/>)}<Route path="*" element={<Navigate to="/login" replace/>}/></Routes>}
export function ProductionApp(){const[state,setState]=useState<AuthState>({status:"checking"}),[client]=useState(()=>new QueryClient());useEffect(()=>{document.documentElement.lang="ar";document.documentElement.dir="rtl";void getSession().then(session=>setState({status:"authenticated",session})).catch(()=>setState({status:"anonymous"}));},[]);return <QueryClientProvider client={client}><div className="production-root" lang="ar" dir="rtl"><BrowserRouter><AppRoutes state={state} onLogin={session=>setState({status:"authenticated",session})}/></BrowserRouter></div></QueryClientProvider>}
