import { useEffect, useState, type ReactNode } from "react";
import "./production.css";
import { BrowserRouter, Navigate, NavLink, Route, Routes, useNavigate } from "react-router";
import { KeyboardInput, MobileScroll } from "../mobile";
import { CommitmentRail, CommitmentRailItem, LedgerRow, LifecycleMiniRail, NextActionHero, StatePanel, StatusLabel } from "../design-system/foundation";
import { getSession, login, type SessionIdentity } from "../lib/api";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { CustomerOperatingFile, CustomerRegister } from "../features/customers/CustomerCore";
import { RepresentativeWorkspace } from "../features/representative/RepresentativeWorkspace";

const roles = [["sales-representative", "مندوب مبيعات", "sales_representative"], ["telesales", "موظف مبيعات هاتفية", "telesales_employee"], ["supervisor", "مشرف مبيعات هاتفية", "telesales_supervisor"], ["manager", "مدير مبيعات", "sales_manager"]] as const;
type AuthState = { status: "checking" } | { status: "anonymous" } | { status: "authenticated"; session: SessionIdentity };

function LoginRoute({ onLogin }: { onLogin: (session: SessionIdentity) => void }) {
  const navigate = useNavigate(); const [email, setEmail] = useState("rep@local.test"); const [password, setPassword] = useState(""); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  return <MobileScroll className="production-screen"><main className="production-login"><NextActionHero eyebrow="منظومة المبيعات" title="تسجيل الدخول" detail="الوصول محمي حسب الدور والنطاق التشغيلي." /><form onSubmit={async (event) => { event.preventDefault(); setSaving(true); setError(null); try { const session = await login(email, password); onLogin(session); const route = roles.find(([, , role]) => role === session.employee.role)?.[0] ?? "sales-representative"; navigate(`/app/${route}`, { replace: true }); } catch (cause) { setError(cause instanceof Error ? cause.message : "تعذر تسجيل الدخول."); } finally { setSaving(false); } }}><label>البريد الإلكتروني<KeyboardInput value={email} onChange={(event) => setEmail(event.target.value)} autoComplete="username" /></label><label>كلمة المرور<KeyboardInput value={password} onChange={(event) => setPassword(event.target.value)} type="password" autoComplete="current-password" /></label>{error && <StatePanel kind="error" title="تعذر تسجيل الدخول" detail={error} />}<button className="production-primary" type="submit" disabled={saving}>{saving ? "جارٍ التحقق…" : "تسجيل الدخول"}</button></form><p className="production-caption">واجهة Phase 0: مسارات وهيكل وصول فقط؛ لا توجد شاشات تشغيلية بعد.</p></main></MobileScroll>;
}
function RolePlaceholder({ role, session }: { role: string; session: SessionIdentity }) { const [customerId,setCustomerId]=useState<string|null>(null);const isRep=session.employee.role==="sales_representative";return <div className="production-app-shell"><header className="production-appbar"><span className="production-kicker">منظومة المبيعات</span><strong>{role}</strong><StatusLabel attention="normal">{session.employee.displayName}</StatusLabel></header><MobileScroll className="production-screen"><main className="production-content">{isRep?(customerId?<CustomerOperatingFile id={customerId} onBack={()=>setCustomerId(null)}/>:<><RepresentativeWorkspace session={session}/><CustomerRegister onOpen={setCustomerId}/></>):<StatePanel kind="empty" title="مسار الدور مهيأ" detail="لا توجد وظائف تشغيلية لهذا الدور في Phase 2."/>}</main></MobileScroll><nav className="production-nav" aria-label="أدوار التطبيق">{roles.map(([path, label]) => <NavLink key={path} to={`/app/${path}`}>{label}</NavLink>)}</nav></div>; }
function Guard({ state, role, children }: { state: AuthState; role: string; children: ReactNode }) { if (state.status === "checking") return <StatePanel kind="loading" title="جارٍ التحقق من الجلسة" detail="يتم تحميل الوصول المصرح به." />; if (state.status === "anonymous") return <Navigate to="/login" replace />; if (state.session.employee.role !== role) return <StatePanel kind="denied" title="غير مصرح" detail="لا تملك صلاحية الوصول إلى مساحة هذا الدور." />; return children; }
function AppRoutes({ state, onLogin }: { state: AuthState; onLogin: (session: SessionIdentity) => void }) { return <Routes><Route path="/login" element={state.status === "authenticated" ? <Navigate to="/app/sales-representative" replace /> : <LoginRoute onLogin={onLogin} />} />{roles.map(([path, label, role]) => <Route key={path} path={`/app/${path}`} element={<Guard state={state} role={role}><RolePlaceholder role={label} session={state.status === "authenticated" ? state.session : { employee: { id: "", displayName: "", role: "" }, csrfToken: "" }} /></Guard>} />)}<Route path="*" element={<Navigate to="/login" replace />} /></Routes>; }
export function ProductionApp() { const [state, setState] = useState<AuthState>({ status: "checking" }); const [client]=useState(()=>new QueryClient());useEffect(() => { document.documentElement.lang = "ar"; document.documentElement.dir = "rtl"; void getSession().then((session) => setState({ status: "authenticated", session })).catch(() => setState({ status: "anonymous" })); }, []); return <QueryClientProvider client={client}><div className="production-root" lang="ar" dir="rtl"><BrowserRouter><AppRoutes state={state} onLogin={(session) => setState({ status: "authenticated", session })} /></BrowserRouter></div></QueryClientProvider>; }
