CREATE TYPE visit_status AS ENUM ('planned','in_progress','completed','cancelled');
CREATE TYPE order_lifecycle_status AS ENUM ('recorded','credit_review','approved','preparation','delivery_preparation','delivered','closed');
CREATE TYPE complaint_status AS ENUM ('recorded','assigned','corrective_action','follow_up','resolved','closed');

CREATE TABLE products (id UUID PRIMARY KEY, organization_id UUID NOT NULL REFERENCES organizations(id), reference_code TEXT NOT NULL, name TEXT NOT NULL, active BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(organization_id,reference_code));
CREATE TABLE visits (id UUID PRIMARY KEY, organization_id UUID NOT NULL REFERENCES organizations(id), customer_id UUID NOT NULL REFERENCES customers(id), representative_id UUID NOT NULL REFERENCES employees(id), planned_at TIMESTAMPTZ NOT NULL, purpose TEXT NOT NULL, status visit_status NOT NULL DEFAULT 'planned', started_at TIMESTAMPTZ, completed_at TIMESTAMPTZ, outcome TEXT, evidence TEXT, notes TEXT, idempotency_key TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK ((status='completed' AND completed_at IS NOT NULL AND outcome IS NOT NULL AND evidence IS NOT NULL) OR (status <> 'completed' AND completed_at IS NULL)), UNIQUE(representative_id,idempotency_key));
CREATE TABLE opportunities (id UUID PRIMARY KEY, organization_id UUID NOT NULL REFERENCES organizations(id), customer_id UUID NOT NULL REFERENCES customers(id), visit_id UUID REFERENCES visits(id), owner_employee_id UUID NOT NULL REFERENCES employees(id), kind TEXT NOT NULL, product_reference TEXT, note TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open','won','deferred')), commitment_id UUID REFERENCES commitments(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE sales_orders (id UUID PRIMARY KEY, organization_id UUID NOT NULL REFERENCES organizations(id), customer_id UUID NOT NULL REFERENCES customers(id), visit_id UUID REFERENCES visits(id), recorded_by_employee_id UUID NOT NULL REFERENCES employees(id), status order_lifecycle_status NOT NULL DEFAULT 'recorded', request_note TEXT, duplicate_override_reason TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE sales_order_items (id UUID PRIMARY KEY, order_id UUID NOT NULL REFERENCES sales_orders(id) ON DELETE CASCADE, product_id UUID NOT NULL REFERENCES products(id), quantity NUMERIC(12,2) NOT NULL CHECK(quantity>0), unit_price NUMERIC(14,2), created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE collection_outcomes (id UUID PRIMARY KEY, organization_id UUID NOT NULL REFERENCES organizations(id), customer_id UUID NOT NULL REFERENCES customers(id), visit_id UUID REFERENCES visits(id), representative_id UUID NOT NULL REFERENCES employees(id), outcome TEXT NOT NULL CHECK(outcome IN ('collected','partial','promise','no_collection')), amount_collected NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK(amount_collected>=0), promise_amount NUMERIC(14,2), promise_due_at TIMESTAMPTZ, evidence TEXT NOT NULL, commitment_id UUID REFERENCES commitments(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK ((outcome='promise' AND promise_amount>0 AND promise_due_at IS NOT NULL) OR outcome<>'promise'));
CREATE TABLE complaints (id UUID PRIMARY KEY, organization_id UUID NOT NULL REFERENCES organizations(id), customer_id UUID NOT NULL REFERENCES customers(id), visit_id UUID REFERENCES visits(id), recorded_by_employee_id UUID NOT NULL REFERENCES employees(id), classification TEXT NOT NULL, description TEXT NOT NULL, responsible_party TEXT, required_action TEXT, status complaint_status NOT NULL DEFAULT 'recorded', follow_up_at TIMESTAMPTZ, escalation_note TEXT, commitment_id UUID REFERENCES commitments(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE market_observations (id UUID PRIMARY KEY, organization_id UUID NOT NULL REFERENCES organizations(id), customer_id UUID REFERENCES customers(id), visit_id UUID REFERENCES visits(id), reported_by_employee_id UUID NOT NULL REFERENCES employees(id), competitor TEXT, product_reference TEXT, competitor_price NUMERIC(14,2), offer TEXT, observation_type TEXT NOT NULL, note TEXT NOT NULL, observed_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX visits_rep_day ON visits(representative_id,planned_at); CREATE INDEX orders_customer_item_lookup ON sales_orders(customer_id,created_at DESC); CREATE INDEX complaint_open_scope ON complaints(customer_id,status); CREATE INDEX observations_scope ON market_observations(organization_id,observed_at DESC);
